### ISSUE TITLE
usbipd error loading vhci_hcd failed

### ISSUE THREAD

**Issue by LZY-SPCA** [dorssel/usbipd-win#1010]
usbipd error loading vhci_hcd failed while attach usb device to wsl

**Comment by LZY-SPCA** [comment]
usbipd-win version
![image](https://github.com/user-attachments/assets/2031698c-4788-4c32-9621-aba375215a5e)
windows 11 23H2

**Comment by dorssel** [comment]
Within WSL, what is the output of `zgrep CONFIG_USBIP /proc/config.gz`?

**Comment by michal5520pl** [comment]
@dorssel
`> zgrep CONFIG_USBIP /proc/config.gz
CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1
CONFIG_USBIP_HOST=m
# CONFIG_USBIP_DEBUG is not set`

I have the same problem with WSL2 pre-release
`Wersja podsystemu WSL: 2.3.14.0
Wersja jądra: 6.6.36.3-1
Wersja usługi WSLg: 1.0.64
Wersja MSRDC: 1.2.5326
Wersja Direct3D: 1.611.1-81528511
Wersja DXCore: 10.0.26100.1-240331-1435.ge-release
Wersja systemu Windows: 10.0.22631.3880`

Apologies for Polish, but I hope it's readable

PS. I have the same version as @LZY-SPCA

**Comment by dorssel** [comment]
What happens if you load the module by hand: `sudo modprobe vhci_hcd`?

**Comment by michal5520pl** [comment]
No module vhci_vhd found, unfortunately. Did Microsoft some fail regarding that module? I will try to compare versions, maybe

**Comment by dorssel** [comment]
Normal (non-pre-release) versions of WSL don't use modules, they have all drivers compiled in a monolithic kernel.

The pre-release version of WSL is switching to modules (`CONFIG_USBIP_CORE=m`), so you will have to load `vhci_hcd`. `usbipd-win` will try to do that automatically. If you don't have that module, there is nothing I can do about it.

**Comment by LZY-SPCA** [comment]
I ran modprobe vhci_hcd successfully and solved this problem.

**Comment by michal5520pl** [comment]
I've tried again and modprobe vhci_hcd indeed worked. Probably I have mismatched one letter due to tiredness. I have resolved the problem with putting .conf file in /etc/modules-load.d with vhci_hcd inside

**Comment by kingsoftech** [comment]
hello everyone am currently facing the same issue with the following output 
CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1
# CONFIG_USBIP_HOST is not set
# CONFIG_USBIP_DEBUG is not set

**Comment by Morrigan-Ship** [comment]
same

sudo modprobe vhci_hcd:

CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1

**Comment by Morrigan-Ship** [comment]
fixed! solved!

run command as Administrator :/

**Comment by zerobinhi** [comment]
# Compile the WSI Linux kernel
```bash
make menuconfig KCONFIG_CONFIG=Microsoft/config-wsl
```

（1）进入 Device Drivers -> USB Support

（2）找到 Support for Host-side USB，键入 “y”

（3）找到 USB/IP Support -> VCHI hcd.

![Image](https://github.com/user-attachments/assets/80dfeaef-3723-438a-82ef-ec1000b23908)

（4）找到 USB Mass Storage support，将其子条目全部选中

![Image](https://github.com/user-attachments/assets/e7b30fe1-0ab7-4616-87d1-c2d5bd0d4202)
用这个新编译的内核即可

![Image](https://github.com/user-attachments/assets/13d1ae89-9a24-4079-b5d8-e8ab9c924e91)
[参考链接](https://www.cnblogs.com/guan88/articles/18619901)

**Comment by Ircon** [comment]
wsl2 (version 2.5.8.0) supports the stick(U盘 in chinese) and ft232 defaultly.
The version is shown in picture.

![Image](https://github.com/user-attachments/assets/ea2f10f6-7a5b-4647-97c6-e78e9e1fdd17)

in wsl2, the bash output is 
```bash
~$ uname -r
6.6.87.1-microsoft-standard-WSL2
```
the output from powershell in win11 is
```bash
$ wsl --version
WSL 版本: 2.5.8.0
内核版本: 6.6.87.1-1
WSLg 版本: 1.0.66
MSRDC 版本: 1.2.6074
Direct3D 版本: 1.611.1-81528511
DXCore 版本: 10.0.26100.1-240331-1435.ge-release
Windows: 10.0.26100.4061
```

You can fix above problems by updating your wsl version.

**Comment by MightyM17** [comment]
> ~$ uname -r
> 6.6.87.1-microsoft-standard-WSL2
> 
> the output from powershell in win11 is
> 
> $ wsl --version
> WSL 版本: 2.5.8.0
> 内核版本: 6.6.87.1-1
> WSLg 版本: 1.0.66
> MSRDC 版本: 1.2.6074
> Direct3D 版本: 1.611.1-81528511
> DXCore 版本: 10.0.26100.1-240331-1435.ge-release
> Windows: 10.0.26100.4061
> 
> You can fix above problems by updating your wsl version.

I cannot update my wsl kernel version
```
wsl --version
WSL version: 2.5.9.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.66
MSRDC version: 1.2.6074
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.4351
```

```
mighty@mighty:$ sudo modprobe vhci-hcd
[sudo] password for mighty:
modprobe: FATAL: Module vhci-hcd not found in directory /lib/modules/6.6.36.6-microsoft-standard-WSL2+
mighty@mighty:$ zgrep CONFIG_USBIP /proc/config.gz
CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1
CONFIG_USBIP_HOST=m
# CONFIG_USBIP_DEBUG is not set
mighty@mighty:$ uname -r
6.6.36.6-microsoft-standard-WSL2+
```

Will try building the WSL kernel now

**Comment by zerobinhi** [comment]
> I cannot update my wsl kernel version
> Will try building the WSL kernel now

@MightyM17 
To be frank, the recognition of removable storage media is already supported in WSL2 2.5.9.
[WSL2](https://github.com/microsoft/WSL/releases/tag/2.5.9)

**Comment by ivbaklan2012** [comment]
> > ~$ uname -r
> > 6.6.87.1-microsoft-standard-WSL2
> > the output from powershell in win11 is
> > $ wsl --version
> > WSL 版本: 2.5.8.0
> > 内核版本: 6.6.87.1-1
> > WSLg 版本: 1.0.66
> > MSRDC 版本: 1.2.6074
> > Direct3D 版本: 1.611.1-81528511
> > DXCore 版本: 10.0.26100.1-240331-1435.ge-release
> > Windows: 10.0.26100.4061
> > You can fix above problems by updating your wsl version.
> 
> I cannot update my wsl kernel version
> 
> ```
> wsl --version
> WSL version: 2.5.9.0
> Kernel version: 6.6.87.2-1
> WSLg version: 1.0.66
> MSRDC version: 1.2.6074
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.26100.1-240331-1435.ge-release
> Windows version: 10.0.26100.4351
> ```
> 
> ```
> mighty@mighty:$ sudo modprobe vhci-hcd
> [sudo] password for mighty:
> modprobe: FATAL: Module vhci-hcd not found in directory /lib/modules/6.6.36.6-microsoft-standard-WSL2+
> mighty@mighty:$ zgrep CONFIG_USBIP /proc/config.gz
> CONFIG_USBIP_CORE=m
> CONFIG_USBIP_VHCI_HCD=m
> CONFIG_USBIP_VHCI_HC_PORTS=8
> CONFIG_USBIP_VHCI_NR_HCS=1
> CONFIG_USBIP_HOST=m
> # CONFIG_USBIP_DEBUG is not set
> mighty@mighty:$ uname -r
> 6.6.36.6-microsoft-standard-WSL2+
> ```
> 
> Will try building the WSL kernel now

try `sudo modprobe vhci_hcd` and not vhci-hcd
