### ISSUE TITLE
What is a "persisted" device?

### ISSUE THREAD

**Issue by znmeb** [dorssel/usbipd-win#1024]
I have `usbipd 4.1.0` running on my Windows 11 Pro system. When I do `usbipd list`, I see this:

```
usbipd list
Connected:
BUSID  VID:PID    DEVICE                                                        STATE
1-13   187c:0550  USB Input Device                                              Not shared
1-14   8087:0026  Intel(R) Wireless Bluetooth(R)                                Not shared
1-24   152d:0578  USB Attached SCSI (UAS) Mass Storage Device                   Not shared
2-4    05e3:0749  USB3.0 Card Reader                                            Not shared
6-4    046d:c52b  Logitech USB Input Device, USB Input Device, Logitech Uni...  Not shared

Persisted:
GUID                                  DEVICE
4b66a1e4-c94d-4569-8e5b-5af5f0b9ba64  USB Mass Storage Device
b52fc97c-924f-4551-b92f-045597f5da55  USB Mass Storage Device, RP2 Boot
bac136dd-d16c-4d87-9e3b-5f6a6d0bc58c  USB Serial Device (COM10)
```

What is a persisted device? How can I get rid of the bottom two - they came from a Raspberry Pi Pico device that is no longer connected to the machine.

**Comment by dorssel** [comment]
Those are devices that you once bound (i.e., made available for sharing), but are currently not connected physically to the host. You can look at them as "remembered devices". If you plug them in, they can be attached immediately (i.e., it remembers that you have already bound them).

To cleanup, you can use `usbipd unbind -g`.
