### ISSUE TITLE
could not connect to port 3240：system error

### ISSUE THREAD

**Issue by coffee-xzm** [dorssel/usbipd-win#1034]
Hi,
The error message I am getting is:
`usbip: error: could not connect to 8.8.8.8:3240: System error`
when running `sudo usbip  list --remote=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}') `
according to (https://github.com/phuoctan4141/WSL/blob/main/Connect%20USB%20devices/USB%20Camera.md)
and debug messages ended as follows:
![image](https://github.com/user-attachments/assets/b8b64a66-e88e-4e1b-bcea-0247500c478b)

I'm a beginner and I have no idea  how to track bugs.
Can you please advise on how to fix?And please inform me of my improper post.
Thanks

**Comment by dorssel** [comment]
8.8.8.8 is your nameserver; it is, in fact, a Google DNS server. So, you are trying to attach an USB device from them. I'm quite sure they do not offer USBIP services. You need the IP address of your host that physically has the USB connected to it.

**Comment by coffee-xzm** [comment]
> 8.8.8.8 is your nameserver; it is, in fact, a Google DNS server. So, you are trying to attach an USB device from them. I'm quite sure they do not offer USBIP services. You need the IP address of your host that physically has the USB connected to it.

your sincere advice helped me a lot, thanks
