### ISSUE TITLE
usbipd: error: The VBoxUsbMon driver is currently not running; a reboot should fix that.

### ISSUE THREAD

**Issue by Zazmi2** [dorssel/usbipd-win#1038]
Hi I am getting the error: usbipd: error: The VBoxUsbMon driver is currently not running; a reboot should fix that. I have tried rebooting my system, uninstalling and reinstalling usbipd. I am able to bind the device but not attach when doing this: usbipd attach --wsl --busid 1-4 and I get no output when running sc query VBoxUsMon.

I am using a surface pro laptop Windows 11 arm64 processor and I am using WSl2.

<img width="596" alt="image" src="https://github.com/user-attachments/assets/69f9c786-67ff-44de-b57f-32720f317f33">

**Comment by dorssel** [comment]
There is something wrong with your Windows service manager: either it should give you a status about VBoxUsbMon (whether it is running or not), or it should complain that the service is not installed at all. The fact that it does not say anything is problematic.

I do remember that someone had similar problems where it turned out to be that another 'sc' executable was in the PATH.

Try running explicitly the Windows service manager as:
```
. $env:windir\system32\sc.exe query VBoxUsbMon
```

**Comment by Zazmi2** [comment]
Hi, this is what I get: 
<img width="661" alt="image" src="https://github.com/user-attachments/assets/cfde2695-96bb-4999-9208-448f16afd4c8">

**Comment by Lewiscowles1986** [comment]
Okay, so I am seeing this using windows 11 arm64. I wonder if others are perhaps using a different architecture?

```
SERVICE_NAME: VBoxUsbMon
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1275  (0x4fb)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by Lewiscowles1986** [comment]
my error when trying to start the service is also different

```
PS C:\Windows\system32> Start-Service VBoxUsbMon
Start-Service : Service 'VirtualBox USB Monitor Service (VBoxUsbMon)' cannot be started due to the following error:
Cannot start service VBoxUsbMon on computer '.'.
At line:1 char:1
+ Start-Service VBoxUsbMon
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

```

**Comment by Lewiscowles1986** [comment]
According to https://github.com/dorssel/usbipd-win/issues/1023#issuecomment-2310041856 this is win64 only, as it uses VirtualBox components. If true, then I've got my answer.

**Comment by dorssel** [comment]
> 

From https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--1000-1299-

```
ERROR_DRIVER_BLOCKED

1275 (0x4FB)

This driver has been blocked from loading.
```

**Comment by Lewiscowles1986** [comment]
Sorry, are you saying it should load and work, on arm64, or that it still should not?

**Comment by dorssel** [comment]
@Lewiscowles1986 

From the README, very first line:

> This software requires Microsoft Windows 10 (x64 only)

From WSL documentation (https://learn.microsoft.com/en-us/windows/wsl/connect-usb), second prerequisite:

> A machine with an x64 processor is required. (x86 and Arm64 are currently not supported with usbipd-win).

From any search in the issue list about ARM64

https://github.com/dorssel/usbipd-win/issues?q=is%3Aissue+arm64

**Comment by Lewiscowles1986** [comment]
Right, except I had to find your github, which was linked via the releases page, not your README; from the microsoft page, where the text is NOT prominently displayed. In fact I wasn't forced to read it and it wasn't called out. Don't feel bad, I've found other software that seems to grant me similar https://github.com/vadimgrn/usbip-win2 and does work with ARM

Thank you for creating what you have created, you have no obligation to help anyone, but I am pointing out that this is most unhelpful, your responses have been less than clear. A Simple No would have also done just as well as the above 2 comments.

**Comment by Lewiscowles1986** [comment]
![Screenshot 2024-10-01 at 08 06 47](https://github.com/user-attachments/assets/d3db9f14-1f86-4acd-b342-dc00aa5b2714)
![Screenshot 2024-10-01 at 08 06 56](https://github.com/user-attachments/assets/a08ff6c5-7917-4ef7-8221-9204262126fc)

**Comment by dorssel** [comment]
@Zazmi2
OP, are you also using ARM64?

**Comment by Zazmi2** [comment]
Yep using arm64

**Comment by PURESUN-OYLY** [comment]
Anyone fix this issue? I also use ARM64 CPU

**Comment by PURESUN-OYLY** [comment]
> > Right, except I had to find your github, which was linked via the releases page, not your README; from the microsoft page, where the text is NOT prominently displayed. In fact I wasn't forced to read it and it wasn't called out. Don't feel bad, I've found other software that seems to grant me similar https://github.com/vadimgrn/usbip-win2 and does work with ARM
> > Thank you for creating what you have created, you have no obligation to help anyone, but I am pointing out that this is most unhelpful, your responses have been less than clear. A Simple No would have also done just as well as the above 2 comments.
> 
> How did you use this to forward usb device windows (WOA)-> Linux wsl @Lewiscowles1986 ? from my understanding USBIP-win2 is a USB/IP client for Windows that allows Windows to connect to USB devices shared from Linux servers. It does not support sharing Windows USB devices to WSL?
> 
> Did you manage to get it to work for that purpose? forward device from host to wsl?

I did not find anyway use usbipd on wsl2, i changed my wsl to version 1, then used uart by ttyUARTx. And i have been tested that usbipd can work well on wsl2 with x86 CPU

**Comment by Lewiscowles1986** [comment]
Oh I love this. I was just last week setting up virtualbox on my apple silicon, and now it seems that work is also benefitting windows on ARM ❤

**Comment by Lewiscowles1986** [comment]
Update: September 2025 - it looks like usbipd now supports arm64, so also https://github.com/MicrosoftDocs/WSL/issues/2032 (pending confirmation my side) should also work
