### ISSUE TITLE
Unable to connect USB to WSL

### ISSUE THREAD

**Issue by jramiresbrito** [dorssel/usbipd-win#107]
Following the post [https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/](https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/)

I've installed **usbipd-win_1.2.0**.
Successfully listed the devices with PowerShell

```bash
PS C:\WINDOWS\system32> usbipd wsl list
BUSID  DEVICE                                                        STATE
1-5    ADB Device, SM-J500M, USB Serial Device                       Not attached
1-8    Microsoft Hardware USB Keyboard, USB Input Device             Not attached
1-9    Intel(R) Wireless Bluetooth(R)                                Not attached
1-10   USB Input Device, WinUsb Device                               Not attached
1-12   USB Input Device                                              Not attached
1-13   USB Input Device
```

Unfortunatelly, when I try to attach:

```bash
usbipd wsl attach -b 1-5

WARNING: usbip not found for kernel 5.10.74.3-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.74.3-microsoft-standard-WSL2
    linux-cloud-tools-5.10.74.3-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
usbipd: error: Failed to attach device with ID '1-5'.
```

Back to WSL2, I've tried to install the packages, but they are not listed:

```bash
sudo apt install linux-tools-5.10.74.3-microsoft-standard-WSL2

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-tools-5.10.74.3-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-tools-5.10.74.3-microsoft-standard-WSL2'
```

How to proceed?

### Environment
Windows: 21H2 (OS Build: 22000.318)
WSL: WSL Preview (the one from store), Ubuntu 20.04.3 LTS

**Comment by dorssel** [comment]
Have a look at https://github.com/dorssel/usbipd-win/wiki/WSL-support.

Depending on your distribution, you will either have to install usbip through the package mentioned there, or you will have to recompile the WSL kernel.

Also have a look at what others did to get their specific distribution to work:
#67 
#99

**Comment by dorssel** [comment]
Closing. Already documented on how to resolve.

**Comment by plutonium-239** [comment]
i still get the same message and nothing seems to fix it
its not a matter of distribution because i have ubuntu 20.04 as used everywhere in the tutorial.
but `sudo apt install linux-tools-virtual hwdata` installs `linux-tools-5.4.0-109` `linux-tools-5.4.0-109-generic`
what should i do?

**Comment by dorssel** [comment]
@plutonium-239 
Following https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools, you installed `linux-tools-virtual`. But because the version does not exactly match the WSL kernel, the second line is needed to tell Ubuntu that you want this version of `usbip` anyway, even if the version does not match exactly:

> sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/*/usbip 20

After that, `usbip` should work. If it doesn't, can you give the output of `ls /usr/lib/linux-tools/`?

**Comment by plutonium-239** [comment]
It just shows one directory: `5.4.0-109-generic`

**Comment by dorssel** [comment]
Does the update-alternatives give any errors? What is the output of a plain `usbip` command on WSL?

**Comment by plutonium-239** [comment]
The `update-alternatives` runs without any errors.
`usbip` shows the help page of usbip, i.e.
```
usage: usbip [--debug] [--log] [--tcp-port PORT] [version]
             [help] <command> <args>

  attach     Attach a remote USB device
  detach     Detach a remote USB device
  list       List exportable or local USB devices
  bind       Bind device to usbip-host.ko
  unbind     Unbind device from usbip-host.ko
  port       Show imported USB devices
```
However, `usbipd` still doesn't work

**Comment by dorssel** [comment]
@plutonium-239 
How many WSL instances do you have? What is the output of (Windows side) `wsl --list`? Are you sure you are using `usbipd wsl attach` on the same instance where you set up usbip? Are you perhaps using docker?

**Comment by plutonium-239** [comment]
I only have one wsl instance, `wsl --list` confirms that (just Ubuntu 20.04)
No, I'm not using docker or anything like that, its a plain and fresh wsl install.
I would be able to do `usbipd wsl attach` only when `usbipd` is recognized

**Comment by dorssel** [comment]
@plutonium-239 
Ok, let's start from the beginning... Your very first sentence in this conversation:

> i still get the same message and nothing seems to fix it

What exactly is that 'same message'? The OP (from 5 month ago) started with a message from `usbipd wsl attach`. And now you tell me that you cannot even run 'usbipd'. So, that confuses me...

**Comment by plutonium-239** [comment]
The "same" message is caused by `usbipd` not being found, even in OP's case (so obviously `usbipd wsl attach` wont work : 
```
 WARNING: usbipd not found for kernel 5.10.102.1-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.102.1-microsoft-standard-WSL2
    linux-cloud-tools-5.10.102.1-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
```
However, one difference is that OP's error pertains to `usbip` not being found too, which is not the case for me.

**Comment by dorssel** [comment]
@plutonium-239 
Ah, that's very simple (and not the same as the OP). You're supposed to run `usbipd` on the Windows side!

**Comment by plutonium-239** [comment]
Oh
well...
Thanks!

**Comment by staffnetDev** [comment]
it work 
wsl 2 

sudo apt install linux-tools-virtual hwdata
sudo update-alternatives --install /usr/local/bin/usbip usbip $(command -v ls /usr/lib/linux-tools/*/usbip | tail -n1) 20

**Comment by NoSubstitute** [comment]
For me, I have to run usbip with sudo in WSL. If I don't, I get the same error message.

```
$ usbip port
WARNING: usbip not found for kernel 6.18.33.2-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-6.18.33.2-microsoft-standard-WSL2
    linux-cloud-tools-6.18.33.2-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
```

With sudo it works fine.

```
$ sudo usbip port
Imported USB devices
====================
Port 00: <Port in Use> at Full Speed(12Mbps)
       Yubico.com : Yubikey 4/5 OTP+U2F+CCID (1050:0407)
       1-1 -> usbip://172.25.16.1:3240/4-1
           -> remote bus/dev 004/001
```

Also the simple lsusb works fine.

```
$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 1050:0407 Yubico.com Yubikey 4/5 OTP+U2F+CCID
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
```

But I can't use ykman (to manage the attached Yubikey) at all, with or without sudo.

```
$ sudo ykman list
WARNING: PC/SC not available. Smart card (CCID) protocols will not function.
ERROR: Unable to list devices for connection
WARNING: No OTP HID backend available. OTP protocols will not function.
ERROR: Unable to list devices for connection
```

```
$ ykman fido info
WARNING: PC/SC not available. Smart card (CCID) protocols will not function.
WARNING: No OTP HID backend available. OTP protocols will not function.
ERROR: No YubiKey detected!
```

```
$ sudo ykman fido info
WARNING: PC/SC not available. Smart card (CCID) protocols will not function.
WARNING: No OTP HID backend available. OTP protocols will not function.
ERROR: No YubiKey detected!
```

pcscd is installed and running.

```
$ sudo service pcscd status
 * pcscd is running
 ```
***
I solved my issues!
```
sudo nano /etc/init.d/pcscd
```
Added this and restarted pcscd service.
```
DAEMON_ARGS="--auto-exit"
```
Not sure if it was absolutely necessary, but in an earlier step, I had added my user to plugdev group so I could run the pcsc_scan command to verify connection with the Yubikey.
```
sudo usermod -aG plugdev $USER
```
And since I was using ykman installed by pip, to get the newest version, I also had to make sure to install and symlink a file.
```
sudo apt install libpcsclite1
sudo ln -s /usr/lib/x86_64-linux-gnu/libpcsclite.so.1 /usr/lib/libpcsclite.so
```
Now _ykman info_ and _ykman list_ work like a charm. :-)
