### ISSUE TITLE
usbipd: error: The specified WSL distribution is not running.

### ISSUE THREAD

**Issue by liquidkey** [dorssel/usbipd-win#126]
Hi,

I am this error when trying to attach usb device

`usbipd: error: The specified WSL distribution is not running.`

**Comment by dorssel** [comment]
Can you post the specific `usbipd wsl attach` command you use, and the output of:

```
wsl --list --all --verbose
```

**Comment by liquidkey** [comment]
:) actually I stumbled upon that command and found that my default distro was not ubuntu. I haven default to ubuntu and I was able to attach.

thanks dorssel

**Comment by liquidkey** [comment]
:) actually I stumbled upon that command and found that my default distro was not ubuntu. I haven default to ubuntu and I was able to attach.

thanks dorsse
