### ISSUE TITLE
USB 3.1 - Failed to attach device (System.IO.FileNotFoundException)

### ISSUE THREAD

**Issue by HackXIt** [dorssel/usbipd-win#161]
I've read issue #63 and also read through #118 but admittedly I was unable to really follow the technical details of the thread.
I created a new issue, in case my problem is unrelated, but I suspect it is similar.

**Info on my setup:**
Debian Bullseye
`5.10.60.1-microsoft-standard-WSL2`
`usbipd-win
1.3.0+37.Branch.master.Sha.89a4e59f384d08d953380913735f59821e63fa1f`

I am unable to attach my microcontroller for flashing, because of the following error:
```
❯ usbipd.exe wsl attach --busid 2-1
[sudo] password for rini-debian:
usbip: error: Attach Request for 2-1 failed - Request Failed

usbipd: error: Failed to attach device with ID '2-1'.
```
The same device/procedure used to work on my previous machine without problems, so I suspected it might have to do something with this new laptop.
Recently I've switched laptops from Surface Pro 6 _(USB 3.0 - USB-A Connector)_ to this new Lenovo Yoga Duet 7 _(USB 3.10 - USB-C / Thunderbolt 4 Connector)_.
I set it up with Windows 11 and my WSL2 Debian Development-Environment.

When attaching the device, the following output can be seen from the usbip server:
```
❯ usbipd server Logging:LogLevel:Default=Trace
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\rini
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: UsbIpServer.Server[1000]
      new connection from 172.17.242.85
dbug: UsbIpServer.ConnectedClient[1000]
      Received opcode: OP_REQ_IMPORT
fail: UsbIpServer.ConnectedClient[3]
      An exception occurred while communicating with the client:
      System.IO.FileNotFoundException: Unable to find the specified file.
         at UsbIpServer.ConfigurationManager.GetVBoxDevice(BusId busId) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConfigurationManager.cs:line 295
         at UsbIpServer.VBoxUsbMon.ClaimDeviceOnce(ExportedDevice device) in D:\a\usbipd-win\usbipd-win\UsbIpServer\VBoxUsbMon.cs:line 141
         at UsbIpServer.VBoxUsbMon.ClaimDevice(ExportedDevice device) in D:\a\usbipd-win\usbipd-win\UsbIpServer\VBoxUsbMon.cs:line 151
         at UsbIpServer.VBoxUsbMon.ClaimDevice(ExportedDevice device) in D:\a\usbipd-win\usbipd-win\UsbIpServer\VBoxUsbMon.cs:line 157
         at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 139
dbug: UsbIpServer.Server[1000]
      connection closed
```

The device I'm trying to attach:
```
❯ usbipd.exe wsl list
BUSID  DEVICE                                                        STATE
2-1    ST-Link Debug, USB Mass Storage Device, Serielles USB-Ger...  Not attached
```
![grafik](https://user-images.githubusercontent.com/1595680/145732363-dd7cc085-d332-4426-8d67-278a9a6aeaa4.png)
![grafik](https://user-images.githubusercontent.com/1595680/145732695-c039bec7-1ae5-429a-86f7-a9a7a4ef665e.png)
![grafik](https://user-images.githubusercontent.com/1595680/145732701-c8cd2daf-192d-496b-b600-951152999355.png)

My drivers are up-to-date as far as I'm aware. I haven't tried installing drivers directly from manufacturer Website, but the Lenovo Driver Update Program didn't notice me about any missing updates, so I suspect it's ok on the driver side.

I would love to learn on how I could fix or troubleshoot this ?

**Comment by HackXIt** [comment]
Just noticed that #118 is also related to USB 3.1, so this issue probably is a duplicate.

**Comment by dorssel** [comment]
Could you post the output of:

```
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}" /v UpperFilters
```

**Comment by HackXIt** [comment]
@dorssel 
```
❯ reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}" /v UpperFilters

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}
    UpperFilters    REG_MULTI_SZ    USBPcap
```

**Comment by dorssel** [comment]
@HackXIt 
I've noticed that some UpperFilters interfere with VBoxUsbMon grabbing the devices. USBPcap (older versions) used to be incompatible with VirtualBox as well. Could you (temporarily) remove USBPcap, or rename the UpperFilters registry key? Then reboot, and try `usbipd-win` again.

**Comment by HackXIt** [comment]
@dorssel
Just did as instructed and now it works, no issue.

So, simple solution would be uninstalling of USBPcap ?
Personally I have no need at the moment, just so happened that I blindly clicked through Wireshark installation and installed that driver too.

**Comment by dorssel** [comment]
@HackXIt 
I don't know how recent your version of USBPcap was. Maybe the latest version is OK, but certainly older versions were incompatible with the VirtualBox drivers. Let me know if you get it to work once you upgrade USBPcap. If the latest version of USBPcap also does not work, then yes, all you can do is uninstall USBPcap.

In any case, glad you have it working now. Please let me know about the USBPcap upgrade, if you are willing to try. If not, I think you can close this issue.

**Comment by HackXIt** [comment]
@dorssel 
I just checked my version: `1.5.4.0`
This appears to be the most recent version, at least from what I can tell on https://github.com/desowin/usbpcap

However, since I'm not using that bit of software anyways, I'll just uninstall it and call it a day. Thank you for the help.
