### ISSUE TITLE
USBIP Device Host Service stopped running(may cause automatic disconnection if not used for a period of time)

### ISSUE THREAD

**Issue by SunJun8** [dorssel/usbipd-win#174]
OS: Windows 11 Pro 22000.376

Version: 1.3.0

Scenes: Share FT2232 to wsl2

Q：USBIP Device Host Service stopped running(may cause automatic disconnection if not used for a period of time)

**Comment by dorssel** [comment]
@SunJun8 
Thank you for the report. Can you find an error/crash report in the Windows Eventlog for this? It could give me a pointer to why it crashed. Was the computer "on" the whole time, or was there any standby/hibernation involved?

**Comment by SunJun8** [comment]
@dorssel 
Sorry I don’t know where the crash log is saved, and the computer does not enter hibernation or standby

**Comment by SunJun8** [comment]
![image](https://user-images.githubusercontent.com/30483934/147799732-7d7209de-1d21-417d-94b0-2a20a87172e0.png)
![image](https://user-images.githubusercontent.com/30483934/147799783-eabeee9d-d990-454e-810a-ca04cd3a0d8c.png)
![image](https://user-images.githubusercontent.com/30483934/147799831-3c62c66b-8ac7-4c3e-a14b-b3ab036e65aa.png)

**Comment by SunJun8** [comment]
Unplug the usb interface without detach, it will probably cause the USBIP Device host to stop service

**Comment by dorssel** [comment]
@SunJun8 
Yes, I understand. It probably has to do with unplugging. Can you please try with the latest master build? The code to deal with unplug detection ha changed, so this bug may have been fixed already. You can find it here: https://github.com/dorssel/usbipd-win/actions/runs/1613336236.

And I think there should be something logged on the Windows side, in Windows Event Viewer (my best guess: 事件查看器).

**Comment by SunJun8** [comment]
Thanks, 1.3.1 work well
