### ISSUE TITLE
Connecting devices to Hyper-V Windows Guests

### ISSUE THREAD

**Issue by sapphire41** [dorssel/usbipd-win#179]
Can we make it possible to access shared devices from Windows VMs?
i.e. have usbipd-win support the `--remote` option so the following could work on Windows guests as well;

```
usbip list --remote=<HOST>
usbip attach --remote=<HOST> --busid=<BUSID>
```

**Comment by dorssel** [comment]
@sapphire41 
No, sorry. See my replies to #65 and #171.
