### ISSUE TITLE
USB Webcam detected by WSL2 but still no /dev/video0

### ISSUE THREAD

**Issue by anmol1ratn** [dorssel/usbipd-win#206]
I followed the instructions and the output of `lsusb` command:
`Bus 001 Device 004: ID 13d3:56eb IMC Networks USB2.0 HD UVC WebCam`

Means that WSL2 has detected the webcam.

But:
```
v4l2-ctl --list-devices
Cannot open device /dev/video0, exiting.
```
```
ls -ltrh /dev/video*
ls: cannot access '/dev/video*': No such file or directory
```
Can you please tell me how to get `/dev/video0` file? Am I missing something?

**Comment by dorssel** [comment]
@anmol1ratn 
By default, the WSL kernel only has USB driver for (some) USB-to-serial devices. It does not have drivers for cameras. You need to build your own kernel, see https://github.com/dorssel/usbipd-win/wiki/WSL-support.

**Comment by anmol1ratn** [comment]
Hi @dorssel 

Forgive my limited knowledge, but why can't I just install the webcam driver with some sudo apt install command?

**Comment by dorssel** [comment]
@anmol1ratn 
That's a complex answer. The short summary: WSL2 uses a monolithic kernel (does not support modules), as WSL instances all share the same kernel (they are essentially dockers). So any driver you want to use must be compiled into that one kernel image.

Sorry, but this is out-of-scope for `usbipd-win`. WSL issues and questions can be asked here: https://github.com/microsoft/WSL

**Comment by biiigwang** [comment]
@anmol1ratn Hello.Have you solved the problem?

**Comment by anmol1ratn** [comment]
No, I couldn't. Compiling a kernel was overkill for my small task.
