### ISSUE TITLE
[2.0.0] minor details

### ISSUE THREAD

**Issue by akuropka** [dorssel/usbipd-win#214]
Hello @dorssel!
Thank you very much for your great efforts in this useful daemon!
Once again me... some very minor things were coming up into my mind:

**[WSL instructions](https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools)**
The package `linux-tools-5.4.0-77-generic` is only available on `bionic` and `focal`. Maybe a more general approach such as `sudo apt install linux-tools-*-generic` would be more standardized for the common user.
I didn't need to apply the `update-alternatives` command after updating but this may be due to the fact that I am building usbip from kernel sources and don't use the `linux-tools`.

**[Release notes](https://github.com/dorssel/usbipd-win/releases/tag/v2.0.0)**
Maybe it would be helpful mentioning that admin rights are required for the first time binding of a device. I immediately ran into this error.
I'm wondering if avoiding evelated commands is really of advantage considering security aspects since root rights are normally required for using usbip client. Omitting the root requirement inside WSL was reasonable since Administrator rights on the host were needed (see [command](https://github.com/dorssel/usbipd-win/pull/74#issuecomment-963127714)) but this is now skipped as well.
As a result I would like to see a setting or switch to keep the requirement of Administrator rights for the following connections.

However, after a first testing it seems everything is working perfectly. Thank you again...!!!

**Comment by dorssel** [comment]
@akuropka 
Thanks for the feedback.

WSL instructions already mention that you need to 'somehow' get `usbip` in the PATH. Current instructions are an example for Ubuntu 20.04 only. Different distros require (slightly) modified instructions. Maybe in the future there will be a wiki page with an overview of known-working distros. For the time being, people can search the issue/discussion lists, just as the instructions already mention.

You need admin rights only for the initial `bind`, e.g. when you use `wsl attach` for the first time. I deliberately do not want people to run `wsl attach` as admin by all the time. That would actually be *less* secure. Once an admin has decided that a device may be shared, I see no reason to further require admin rights for users who already have physical access to the hardware to begin with.
And not requiring a `root` password on the Linux side is perfectly fine. WSL instances are *per user*, so each standard user already has full access to their own WSL instances. After all, they can install, uninstall, or run `wsl --user root` at will. Requiring users to enter a root password would just be a nuisance, or worse, provide a false sense of security.
