### ISSUE TITLE
Uft-8 coding problem

### ISSUE THREAD

**Issue by 1184197761** [dorssel/usbipd-win#240]
When I use **usbipd-win**, it often appears � between Chinese fonts, resulting in dislocation and truncation of display content
![image](https://user-images.githubusercontent.com/56498478/151666595-f7b9a667-6bdb-439b-bb0e-383d14217165.png)

**Comment by 1184197761** [comment]
Although it has little impact, I hope this problem can be solved. Thank you very much

**Comment by dorssel** [comment]
@1184197761 
I do not think this is `usbipd-win` related at all. It seems you are using Windows Terminal, with a WSL session; usbipd-win is not involved there at all. Maybe ask in the Windows Terminal or WSL projects (both are on GitHub).
