### ISSUE TITLE
[2.1.1] usbipd-win cannot be removed by installer

### ISSUE THREAD

**Issue by akuropka** [dorssel/usbipd-win#263]
Installed this version: https://github.com/dorssel/usbipd-win/actions/runs/1814283889
https://user-images.githubusercontent.com/22570574/153762073-baa3d492-5f2a-4c97-81be-00f0a42d0f69.mp4

**Comment by dorssel** [comment]
@akuropka 
Interesting. Can you repeat this with full logging?
```
msiexec -i C:\Windows\Installer\226ca.msi -lvx* C:\uninstall.txt
```

**Comment by akuropka** [comment]
Hi @dorssel,
uninstall was working with the above command and I was not able to reproduce the issue.
I tried several times before and did reboot inbetween but filed before.
Sorry for creating troubles for nothing...
