### ISSUE TITLE
Can I disabled persisted devices?

### ISSUE THREAD

**Issue by d0n13** [dorssel/usbipd-win#272]
Hi @dorssel,

This is a nice piece of software and works really well. I have a question about persisted devices. Our use case involves plugging in phones to test and once we unplug we likely won't need to see that device again. I'm worried about building up a large amount of persisted entries in the registry. 

QUESTIONS: 

- Would it be possible to avoid persisting the device and if so, would it have any other implications? We have had issues with Windows slowing down over time after a lot of devices are added and removed and I've noted that device manager also persists older devices. I guess to improve performance when plugged in again.

- Would it be safe for us to remove the persisted entries from our app and would the usbipd service get upset if we removed them from underneath it? I've looked at the code but it's complex and I don't fully understand the implications of doing this.

Many thanks

**Comment by dorssel** [comment]
@d0n13 
Complex issue --> complex answer ... here goes ...

The "persistence" that `usbipd-win` does is nothing more than a simple registry entry that allows usbipd to remember the device. Even with 1000+ such entries, that is not going to slow down anything. These are in `HKEY_LOCAL_MACHINE\SOFTWARE\usbipd-win\Devices`. Again, that is just administration, it has nothing to do with actual devices or drivers.

Then there is the fact that Window remembers every device ever connected. It does so in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB`. That is not specific to usbipd-win, that always happens. If you are *not* using --force, then there will be 2 such entries in the device tree, one for the original and one for the "stub" device. Those are all named "Vid_80EE&Pid_CAFE" (that's the device ID VirtualBox came up with, Vid_80EE == Oracle).

You can remove the administrative entries of `usbipd-win` with `usbipd unbind --guid`. That will simply remove the registry entry, in effect causing usbipd to "forget" about the device. There is no problem if you unbind a device even if it is currently attached. That will simply cause an immediate detach (USB terminology: Surprise Removal), followed by usbipd "forgetting" about the device.

To get rid of unconnected devices in Windows' memory ... you could use `pnputil /remove-device`. That will clean up the device tree (remember that the device tree contains *all* devices ever connected to your PC, even in the past). `pnputil` also allows you to change/install/remove drivers etc. But this is all not `usbipd-win` related.

**Comment by d0n13** [comment]
Thank you
