### ISSUE TITLE
usbipd: error: The specified WSL distribution is not running.

### ISSUE THREAD

**Issue by SamGeens** [dorssel/usbipd-win#292]
Trying to attach usb devices to wsl fails since insiders build 22567.

Listing the devices works perfect and ` wsl -l -v` shows that the Ubuntu wsl is running.
![image](https://user-images.githubusercontent.com/56310463/157052806-8b399929-d086-468a-823a-b6c77b661c8f.png)

When trying to attach a usb device the following errors occurs: `usbipd: error: The specified WSL distribution is not running.`

**Comment by dorssel** [comment]
@SamGeens 
Notice that `docker-desktop` is the current WSL default. You will either have to use `usbipd wsl attach --distribution Ubuntu`, or change the default with `wsl --setdefault Ubuntu`.

**Comment by SamGeens** [comment]
Thanks! This must have been changed due an update and slipped my eye.
