### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by d0n13** [dorssel/usbipd-win#298]
Just wondering what tools you need to build the whole project from source? Including installers. I just have community edition of VS 2022. It doesn't seem to be enough.

**Comment by dorssel** [comment]
For the software, you only need .NET SDK 6.
For the installer, you only need *any* VS tools (such as your VS 2022 community edition).

Follow build script as in:
https://github.com/dorssel/usbipd-win/blob/master/.github/workflows/build.yml

**Comment by d0n13** [comment]
There is a dependency on .NET 3.5 so when I installed that and turned on the build for the installer it worked in VS 2022

https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net35-sp1-web-installer
