### ISSUE TITLE
usbip: error: Attach Request for 1-2 failed - Device busy (exported)

### ISSUE THREAD

**Issue by Kuhicop** [dorssel/usbipd-win#304]
I'm trying to access my phone from WSL:
![image](https://user-images.githubusercontent.com/27239965/158448925-72eade0e-a957-4b96-9c2a-ff3d0aaa782a.png)

I don't know why I'm getting that error:
usbip: error: Attach Request for 1-2 failed - Device busy (exported)

I did further testing:
![image](https://user-images.githubusercontent.com/27239965/158451862-6951bd63-1432-4053-b1fa-72752f095773.png)

Looks like it won't attach for WSL

Any ideas?

**Comment by dorssel** [comment]
"Device busy" means exactly that. Something on the Windows host is holding an exclusive lock to it. Maybe software, maybe a service, maybe even the native driver itself. If you do not intend to use the device on Windows, you can force binding to the VBoxUsb driver with `usbipd bind --force --busid 1-2`. That may require a reboot, but in the end the device will be permanently claimed by usbipd-win and `wsl attach` should no longer fail.

**Comment by Kuhicop** [comment]
Worked :D

![image](https://user-images.githubusercontent.com/27239965/158473212-52d958ef-0131-403a-9339-7b0129a73156.png)

![image](https://user-images.githubusercontent.com/27239965/158473240-1a70c9c6-dfc3-4988-88a9-0d19049c6d70.png)

Thanks <3
