### ISSUE TITLE
ubdipd and docker container

### ISSUE THREAD

**Issue by salvatoreTorsello** [dorssel/usbipd-win#315]
Hi, 
is there any chance to use usbipd to program a development kit (mine is nrf9160dk) that uses SEGGER JLink drivers? I already tried but i got some problems with udev in containers. 

Thanks. 
Salvo

**Comment by dorssel** [comment]
@salvatoreTorsello 
Search other issues (or better: discussions) for 'docket' and 'udev'. This is not really a usbipd-win issue, but more a WSL question.

**Comment by NikLeberg** [comment]
Hi @salvatoreTorsello
I use usbipd successfully to forward a USB device to a docker container. For that I had to map `-v /dev:/dev` and add `--privileged` so the container can access the devices. Depending on you device you have to install drivers for it in WSL2 thought.

**Comment by salvatoreTorsello** [comment]
> Hi @salvatoreTorsello I use usbipd successfully to forward a USB device to a docker container. For that I had to map `-v /dev:/dev` and add `--privileged` so the container can access the devices. Depending on you device you have to install drivers for it in WSL2 thought.

Ok will try with your suggestion! Are you using only a serial COM port or even a more complex device? Thanks!

**Comment by NikLeberg** [comment]
@salvatoreTorsello It is a STM32 STLink programming probe but it is basically a COM port.

**Comment by dorssel** [comment]
@salvatoreTorsello 
Has this issue been resolved?

**Comment by dorssel** [comment]
Closed due to inactivity.

**Comment by guillaumenibert** [comment]
> Hi @salvatoreTorsello I use usbipd successfully to forward a USB device to a docker container. For that I had to map `-v /dev:/dev` and add `--privileged` so the container can access the devices. Depending on you device you have to install drivers for it in WSL2 thought.

Hello @NikLeberg, I am particularly interested in this discussion. I am looking to share my USB camera to a docker container, I performed these steps:
 - I recompiled the Linux kernel for WSL with camera driver support,
 - then attached my camera to WSL using usbipd,
 - tested the camera on the Ubuntu default WSL distribution with cheese: it works.
 - `/dev/video0` is visible in the `docker-desktop` distro, but not in the container:

I tried these configurations (docker compose file), with or without privileges, with or without devices:
```yml
...
privileged: true
volumes:
   - /dev:/dev
   - /run/desktop/dev:/dev
   - /run/desktop/dev/video0:/dev/video0

devices:
   - /dev:/dev
   - /run/desktop/dev:/dev
   - /dev/video0:/dev/video0
...
```

When I do `lsudb` in my container, the camera is visible, but the output of `ls /dev` does not list `video0`.

I am interested in any advice, whether or not it concerns usbipd or rather WSL/Docker.

Best regards,

Guillaume

--
Docker Desktop for Windows 4.28.0
Usbipd: 4.1.1-dev (from #856)
Host: Windows 11 23H2
Container: Ubuntu 22.04
