### ISSUE TITLE
Auto attach script error

### ISSUE THREAD

**Issue by Uldiniad** [dorssel/usbipd-win#368]
I have seen the following error occasionally when using the -a parameter:
`/mnt/c/Program Files/usbipd-win/wsl-scripts/auto-attach.sh: line 70: 0008: value too great for base (error token is "0008")`

I can reproduce frequently with one of my devices

**Comment by Uldiniad** [comment]
Not sure if relevant but the same device that I can reproduce this on frequently also does not create /dev/ttyUSB0 as it is expected to. I can create a separate issue if wanted

**Comment by dorssel** [comment]
I'll try to solve this over the weekend. We'll see if these are related (I think they are). If not, let's create a separate issue only then.

Thanks for the report.

**Comment by dorssel** [comment]
@Uldiniad 
Could you test the installer at https://github.com/dorssel/usbipd-win/actions/runs/2284505248? That should fix it.

**Comment by Uldiniad** [comment]
Seems to have fixed the error. The auto attach script no longer exits.

**Comment by Uldiniad** [comment]
Is that 2.3.1 package going to be the same as the one in the releases? I installed via winget originally. Can I continue using it after installing the above?

**Comment by Uldiniad** [comment]
> Not sure if relevant but the same device that I can reproduce this on frequently also does not create /dev/ttyUSB0 as it is expected to. I can create a separate issue if wanted

Also, this device seems to switch between 2 bus IDs even though it remains connected to the same port. Is this expected or normal for some devices? Should I open a ticket if these quirks are related this project?

**Comment by dorssel** [comment]
@Uldiniad 
No, this will be in the next release, which will probably by 2.4.0. The ".1" at the end is an artifact from GitVersion auto-numbering. You are now on an (unsigned) development build. When 2.4.0 will be released, `winget upgrade usbipd` should pick it up automatically.

**Comment by dorssel** [comment]
@Uldiniad 
Do you mean 2 different BUSIDs on the Windows side? That would be odd... Maybe if the device is sometimes seen as HighSpeed (USB 2) and sometimes as SuperSpeed (USB 3)...

**Comment by Uldiniad** [comment]
Good question and theory, I'll keep an eye out for that. If that does not explain it I will open a separate issue
