### ISSUE TITLE
can't attach devices on WSL2 / win11

### ISSUE THREAD

**Issue by vincenzoml** [dorssel/usbipd-win#391]
I get the following error when trying to attach a device:

PS C:\Users\vince> usbipd wsl attach --busid 2-2
usbipd: error: WSL 'usbip' client not correctly installed. See https://github.com/dorssel/usbipd-win/wiki/WSL-support for the latest instructions.

note that I have followed the instructions. I use ubuntu 20.04 on wsl2 on windows11. I have also shutted down WSL (from power shell) and restarted it.

**Comment by dorssel** [comment]
How many distro's do you have? Which is the default? Are you using docker? What is the output of `wsl -u root usbip` (when run from Windows)? And  the output of `wsl usbip` (again, from Windows)?

**Comment by vincenzoml** [comment]
Thanks for the prompt reply. I only have ubuntu 20.04, I am not using docker, 

```PS C:\Windows\System32> wsl -u root usbip
WARNING: usbip not found for kernel 5.10.102.1-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.102.1-microsoft-standard-WSL2
    linux-cloud-tools-5.10.102.1-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2```

```PS C:\Windows\System32> wsl usbip
WARNING: usbip not found for kernel 5.10.102.1-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.102.1-microsoft-standard-WSL2
    linux-cloud-tools-5.10.102.1-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2```

**Comment by dorssel** [comment]
What is the output of `ls /usr/lib/linux-tools/` (Linux side)?

**Comment by vincenzoml** [comment]
Oh, that must be because of the "*" which actually creates more arguments to the update-alternatives script than required. This works:

`sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/5.10.0-1021-oem/usbip 20`

but indeed it's unclear which version one should install.

**Comment by dorssel** [comment]
Ideally, there should be only one version of linux-tools installed. What does `dpkg -l | grep linux-tools` give?

**Comment by vincenzoml** [comment]
I'm trying to make https://github.com/Sayobot work on WSL so I guess no specific drivers are needed, as the protocol is custom? It's a re-programmable keyboard. @Sayobot what do you think?

**Comment by dorssel** [comment]
I don't really know. But for a programmable keyboard it seems logical that you would require CONFIG_HIDRAW. However, this is *not* enabled in the default WSL kernel.

**Comment by dorssel** [comment]
I've updated the instruction on the WSL wiki.
