### ISSUE TITLE
Usbipd worked this morning.  Now 'usbipd: error: WSL 'usbip' client not correctly installed'

### ISSUE THREAD

**Issue by quixotictech-dev** [dorssel/usbipd-win#399]
After some struggle I finally got usbipd working correctly with my WSL2 install.  However,  it t seems to have been shortlived.  After reinstalling I still experience this error which is just bizarre.  This morning I was using ADB through Ubuntu but now I can't launch the program.

**Comment by dorssel** [comment]
What distro? Ubuntu? Did you run updates? Maybe a new `usbip` was installed and you have to re-run `update-alternatives`...

**Comment by Jordan-Anjie-Lu** [comment]
Encountered a similar issue. In my instance, `sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/*/usbip 20` wasn't installing properly as my distribution somehow had done...something to itself. See image for reference:
![usbipd-failed-install](https://user-images.githubusercontent.com/49064210/173527930-ae90a7bd-b9ce-4333-bde0-c024b496d65a.png)

Fixed it locally by locating the new location of the file (in my installation, files in `/usr/lib/linux-tools/5.4.0-117-generic` were pointing to files in `/usr/lib/linux-tools-5.4.0-117/`) and modifying the above `sudo` command to match. 
![usbipd-successful-install](https://user-images.githubusercontent.com/49064210/173528483-f4e59cbf-e32c-4110-8999-1e0c9e08ba35.png)

**Comment by dorssel** [comment]
@Jordan-Anjie-Lu 
See https://github.com/dorssel/usbipd-win/issues/391#issuecomment-1135924535

This happens if you have multiple versions of usbip installed. Can you try the command in the link to see if that solves the problem. If so, I will update the wiki.

**Comment by Jordan-Anjie-Lu** [comment]
@dorssel Looks like the command in that link works. Thank you for creating this project!

**Comment by dorssel** [comment]
I've updated the WSL wiki instructions.

@quixotictech-dev 
Has your issue been solved?

**Comment by dorssel** [comment]
Closing (stale).
