### ISSUE TITLE
install linux-tools-virtual fails

### ISSUE THREAD

**Issue by marcin2x4** [dorssel/usbipd-win#406]
When running below I get an error:

`sudo apt install linux-tools-virtual hwdata`

`E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-tools-virtual_5.4.0.64.67_amd64.deb  404  Not Found [IP: 185.125.190.36 80]`

`uname -a for my WSL2`:
`Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
`OS: Win 10 64`

**Comment by dorssel** [comment]
looks like your repo pacakge list needs an update:
```
sudo apt update
```
Then try again.

**Comment by marcin2x4** [comment]
Thanks @dorssel 
Just found this on my end as well :)
