### ISSUE TITLE
PC crashes when using usbipd-win

### ISSUE THREAD

**Issue by d0n13** [dorssel/usbipd-win#410]
Hi all

Just wondering how to go about debugging this. I'm using libimobiledevice on AWS and using a tunnel to communicate with usbipd-win on the pc. That is ok and working and I can retrieve data from the iPhones using it from AWS.

However, when I do a file transfer from AWS to the device using ideviceinstaller -I mobileapp.ipa it runs for a few seconds and then the whole PC blue screens BSOD.

<img width="480" alt="BSOD" src="https://camo.githubusercontent.com/7fc82277a67eb725c7b92cab6a1f53d375cb62b5266ea8b1b3c6effb38da7188/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f352f35362f42736f6477696e646f777331302e706e67">

Anyone seen this behaviour before and know how to even start to debug what might be going wrong? The fact it crashes on the PC side leads me to believe there is a issues on the driver side possibly?

Thanks
Donie

**Comment by dorssel** [comment]
See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xef--critical-process-died
Is there anything in the post-mortem Windows EventLog that tells you *which* process died?
Maybe a driver can cause this too, in which case it may be related to #248.

**Comment by d0n13** [comment]
Just to note that sending a small ipa file works where the larger one causes the crash. Just fyi

**Comment by dorssel** [comment]
Version 3.1.0 (https://github.com/dorssel/usbipd-win/releases/tag/v3.1.0) was released. This should fix the BSOD. Can this be confirmed?
