### ISSUE TITLE
usbip not found in Ubuntu created in Windows 10

### ISSUE THREAD

**Issue by rileyle** [dorssel/usbipd-win#414]
I created a standard WSL2 Ubuntu VM under Windows 10. I have now upgraded to Windows 11, and I am trying to get usbipd-win and usbip working with my existing WSL2 Ubuntu. 

The usbipd-win end is working, listing devices.

In Ubuntu I have done

> sudo apt install linux-tools-virtual hwdata
> sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/*/usbip 20

and shut down / restarted the VM.

When I run usbip in Ubuntu, I get:

> WARNING: usbip not found for kernel 5.10.102.1-microsoft

I take this to mean that USB support isn't in my kernel. Would creating a fresh Ubuntu in Windows 11 fix this, or do I need to compile a kernel?

**Comment by dorssel** [comment]
kernel 5.10.102.1-microsoft is fine, it has USBIP support. Depending on the type of device you want to use you may still have to compile your own kernel. The default WSL kernel has only a limited number of USB drivers built-in.

Regarding:

> WARNING: usbip not found for kernel 5.10.102.1-microsoft

What is the output of (executing in Windows): `wsl --list --verbose`?

**Comment by rileyle** [comment]
> PS C:\Users\lriley> wsl --list --verbose
>   NAME      STATE           VERSION
> * Ubuntu    Stopped         2

To clarify, I created the VM as an Ubuntu WSL2 machine under Windows 10. When I upgraded to Windows 11, I installed WSL from the Windows Store (for WSLg functionality).

**Comment by rileyle** [comment]
Also, `usbipd wsl list` gives a warning:

> usbipd: warning: Unknown USB filter 'tdevflt' may be incompatible with this software; 'bind --force' may be required.

**Comment by dorssel** [comment]
That filter appears to be from Cortex XDR. It just means that dynamically attaching will probably not work. But there is a workaround using `usbipd bind --force` for that. It is an unrelated issue.
