### ISSUE TITLE
usbipd: error: WSL 'usbip' client not correctly installed

### ISSUE THREAD

**Issue by Ps4wicki** [dorssel/usbipd-win#440]
Hi, i tried to attach usb device to wsl by usbipd, and something went wrong, and i can't handle it by myself so I need your help.

![Zrzut ekranu 2022-08-29 115819](https://user-images.githubusercontent.com/64373802/187176159-7313aea8-50d0-4d2e-95c9-666070e3a457.png)

`C:\Users\Piotr Sawicki> usbipd wsl attach --busid 2-1
usbipd: error: WSL 'usbip' client not correctly installed. See https://github.com/dorssel/usbipd-win/wiki/WSL-support for the latest instructions.
PS C:\Users\Piotr Sawicki> wsl --update
Checking for updates...
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.
PS C:\Users\Piotr Sawicki> wsl --user root usbip version
/bin/bash: usbip: command not found
PS C:\Users\Piotr Sawicki> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)`

**Comment by dorssel** [comment]
You really need to execute the following instructions: https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools. This is also what the error says (and it says it for a reason...)
