### ISSUE TITLE
usbipd-win installation in windows 10 caused loss of user profile 

### ISSUE THREAD

**Issue by preenu91** [dorssel/usbipd-win#445]
After building own USB/IP enabled WSL 2 kernel in Windows 10, I lost access to my windows user profile. Windows messed up my login process and I got signed into a temporary profile. I tried restarting many times. In the temporary profile, wsl behaves weirdly. Could you please suggest some solution on this?

**Comment by preenu91** [comment]
Great. Thanks. Why is the installation messing up my original profile? Could you please provide some insights into this

**Comment by dorssel** [comment]
This is unrelated to `usbipd-win`, which doesn't do anything with your profile. And I've also never heard of WSL messing with the user profile either, but you could ask the WSL project at https://github.com/microsoft/WSL.

**Comment by dorssel** [comment]
@preenu91 Any news? If not, I will close this issue as stale.

**Comment by preenu91** [comment]
@dorssel Yes , please close it.
