### ISSUE TITLE
Arm64 devices are not support 

### ISSUE THREAD

**Issue by Gabessat** [dorssel/usbipd-win#486]
![image](https://user-images.githubusercontent.com/118879756/203816337-fa062f99-d1bf-4678-baa8-47d1977f4ad8.png)

**Comment by dorssel** [comment]
By design. See https://github.com/dorssel/usbipd-win/issues/233.

**Comment by dorssel** [comment]
ARM64 support is part of version 5.0.0, which has just been released.
