### ISSUE TITLE
Unable to attach to usb device.

### ISSUE THREAD

**Issue by Incipe-win** [dorssel/usbipd-win#488]

**Comment by Incipe-win** [comment]
Hello usbipd-win team,
I have installed usbip according to the [Microsoft documentation](https://learn.microsoft.com/en-us/windows/wsl/connect-usb), and can view the device information through usbipd. However, when I execute `usbipd wsl attach`, it does not take effect. Here is my screenshot.
![image](https://user-images.githubusercontent.com/46396344/204298208-7920eb5a-6da7-48a8-9b9c-5b8df2ed9aa1.png)
My device is connected to the windows usb through the usb adapter, is this the cause?
Thanks in Advance 🙂

**Comment by dorssel** [comment]
Like the warning says, you will need to use `usbipd bind --force` first...

**Comment by Incipe-win** [comment]
Thank you very much for your reply. 
This warning is because I have installed USBPcap. If I uninstall USBpcap, there will be no Warning. 
But I still can't attach to usb device.
![image](https://user-images.githubusercontent.com/46396344/204540171-5de756ff-be5b-4b6b-b166-ae8183d082cf.png)

**Comment by dorssel** [comment]
1) Can you post the results of `usbipd list` (instead of `usbipd wsl list`)?
2) Can you run `usbipd` with full logging? See https://github.com/dorssel/usbipd-win/wiki/Troubleshooting

**Comment by dorssel** [comment]
Stale
