### ISSUE TITLE
Forwarding iProduct/iManufacturer/iSerial strings

### ISSUE THREAD

**Issue by jamesadevine** [dorssel/usbipd-win#490]
Hiya!

There are many FTDI devices out there on the market today. All FTDI chips observe the same `idVendor` and `idProduct` (dependent on chip) identifiers. Device manufacturers typically store additional metadata in the iManufacturer/iProduct/iSerial strings. Take Azure Sphere (A Microsoft product) on Ubuntu 20.04 for example:

![Screenshot from 2022-11-29 14-05-21](https://user-images.githubusercontent.com/4742697/204550327-5edbae35-48e2-4eaa-a6a4-38f8c774fb21.png)

With WSL2 and usbip, the iManufacturer/iProduct/iSerial strings do not appear for the same device:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/4742697/204550571-fd7fad90-0657-4abb-883d-ca7f1c5f5e87.png">

Is there anything that can be done to forward iManufacturer/iProduct/iSerial strings to WSL? Or is this a technical limitation of the approach taken by usbip?

**Comment by dorssel** [comment]
Those strings are exposed by the device itself *through* USB (i.e. not as metadata, but as actual USB requests). `usbipd` already forwards the entire device, including all its configuration data; and therefore also the string table. So, they are available to WSL as well.

I think you have a permission problem ("Couldn't open device"). Try running with `sudo`, or fix your `udev`.

**Comment by jamesadevine** [comment]
Running `lsusb` with `sudo` showed the strings. This was quite obvious in hindsight. Sorry for the noise and thanks for the awesome work.
