### ISSUE TITLE
failure to attach to WSL Kali instance

### ISSUE THREAD

**Issue by TheProgrammingGamer** [dorssel/usbipd-win#505]
After having looked through some issues I have found what I believe to be the correct packages for my distribution. And after having followed the provided steps I have encountered an error during the attaching process. The error message says that a firewall may be blocking the connection then says there was a TCP connection error. I'm not sure whats going on, so any help would be appreciated. Thanks!

<img width="602" alt="Screenshot 2022-12-13 095902" src="https://user-images.githubusercontent.com/88248878/207382436-a44ef5fe-9ce1-4c04-9aed-387d982be89d.png">

**Comment by dorssel** [comment]
Your *Windows host* needs to be accessible on port 3240. See the main README.

**Comment by dorssel** [comment]
Stale
