### ISSUE TITLE
Hyper-V guest doesn't see host-shared USB device

### ISSUE THREAD

**Issue by Pomax** [dorssel/usbipd-win#511]
I have a Windows 10 pro host with a Hyper-V Windows 10 pro VM client, and on the host machine I've run `usbipd bind --busid=3-4` (a midi keyboard):

```
C:\>usbipd list
Connected:
BUSID  VID:PID    DEVICE                                                        STATE
3-1    1b1c:1b13  USB Input Device                                              Not shared
3-3    231d:011f  USB Input Device                                              Not shared
3-4    1235:0136  LKMK3 MIDI, USB Input Device                                  Shared

Persisted:
GUID                                  DEVICE

```

but running `usbipd list` in the client shows no devices:

```
C:\>usbipd list
Connected:
BUSID  VID:PID    DEVICE                                                        STATE

Persisted:
GUID                                  DEVICE
```

The networking is set to direct share of a physical network card, and both host and client can ping each other on their respective 192.168.1.* addresses, with both machines running the usbipd service.

(Note: tried turning off the windows firewall in the guest entirely, but that didn't have any effect)

**Comment by dorssel** [comment]
`usbipd-win` is only a server. You will need some other software on the Windows *client* side.

**Comment by Pomax** [comment]
any you'd recommend? Because I ended up here after going "sorry, USB Network Gate wants $1200?", and VirtualHere not working for hyper-v

**Comment by dorssel** [comment]
I don't use a Window client, so I wouldn't know. There are some entries in the discussions from people that successfully got it working. In any case, this is not an issue with `usbipd-win`, so I'll close this.

**Comment by Pomax** [comment]
fair, although as a windows usbipd, it would help folks a _lot_ to also mention which windows usbip clients folks can use in the readme, because I've been spending four days trying to find one that actually works with Hyper-V, and apparently none of them do. Which people who need a windows usbipd probably care about a lot.
