### ISSUE TITLE
USB Device Missing From Exportable List from WSL

### ISSUE THREAD

**Issue by mriksman** [dorssel/usbipd-win#524]
Hi,

I used to perform my attach/bind from PowerShell using the command `usbipd wsl attach --busid 4-2`

However, after I bridged my Internet and vSwitch together (using a Hyper-V virtual switch), I get the following error
```
PS C:\WINDOWS\system32> usbipd wsl attach --busid 4-2
usbipd: info: Using default WSL distribution 'Ubuntu'; specify the '--distribution' option to select a different one.
usbipd: error: The local IP address for the WSL virtual switch could not be found.
```

The bridge means that the `wsl` distribution is running on the same subnet as my host. `wsl` `ip a` command
```
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 5c:bb:f6:9e:ee:fa brd ff:ff:ff:ff:ff:ff
    inet 172.20.10.11/28 brd 172.20.10.15 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdfa:fec9:d8ab:45fd:5ebb:f6ff:fe9e:eefa/64 scope global dynamic mngtmpaddr
       valid_lft 1708sec preferred_lft 1708sec
    inet6 fe80::5ebb:f6ff:fe9e:eefa/64 scope link
       valid_lft forever preferred_lft forever
```
And my Windows host `ipconfig`
```
Ethernet adapter vEthernet (hyperv):

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : fdfa:fec9:d8ab:45fd:e6db:7b08:4345:a338
   Temporary IPv6 Address. . . . . . : fdfa:fec9:d8ab:45fd:6832:b036:f703:2648
   Link-local IPv6 Address . . . . . : fe80::7532:a9af:b9a7:d662%26
   IPv4 Address. . . . . . . . . . . : 172.20.10.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . : 172.20.10.1

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::4711:9b55:a5e5:5b3d%23
   IPv4 Address. . . . . . . . . . . : 172.17.16.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
```
The `wsl` distributions are running.
```
PS C:\WINDOWS\system32> wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  wsl2-usbip             Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

No problem, I thought, I can attach/bind it from `wsl` side. At least I thought...
<img width="581" alt="image" src="https://user-images.githubusercontent.com/20112339/212757438-979a86b1-a59e-4cab-ac26-c1aae1647c01.png">

Except, `4-2` is missing. Why is that?

I need help to either;
* Attach/bind from Windows side now that the IP/network is no longer NAT, or
* Find out why I can't attach a serial COM device from the `wsl` side.
  Edit: answer - you must `bind` it or `attach` it at least once on the Windows side before it appears with the `usbip list -r <host_ip>`  command on `wsl`. 

Looking at #84 you say that it looks for a switch with 'WSL' in it...?

**Comment by mriksman** [comment]
I renamed my Virtual Switch to `WSL` and rebooted. I was then able to attach the device from the Windows side.

So `usbip` is hardcoded to look for `WSL` virtual switch? Maybe it should read the `.wsconfig` file to see what switch `wsl` has been configured for?

**Comment by dorssel** [comment]
The current master does that. It will be in the next release.
