### ISSUE TITLE
Arduino Leonardo (Microcontroller) Keeps Disconnecting from Arduino IDE - WL2 usbipd-win

### ISSUE THREAD

**Issue by acruz7439** [dorssel/usbipd-win#532]
Good afternoon,

I've been trying to configure a connection between the Arduino Leonardo to Ubuntu 20.04 WSL2 server. In this depository, I would run a virtual Linux desktop in order to start up an Arduino IDE (1.8.19).

When running usbipd-win, the Arduino IDE in Linux is able to detect the microcontroller. 

NOTE: The left side of the image below showcases the Arduino IDE connected to the Leonardo with usbipd-win. On the right hand side, you can see the connection occuring through the optional GUI for the usbipd-win.

![image](https://user-images.githubusercontent.com/47395555/216661036-4f69dde6-196f-4967-b410-070ed7f28a5c.png)

However, whenever I would try to upload any sort of sketch into the device, it would automatically disconnect from the WSL2.

![image](https://user-images.githubusercontent.com/47395555/216661592-d22f2b02-9e1b-40de-81f4-b85039208d07.png)

Whenever I would try to make the connection between the microcontroller and WSL through administrator or normal terminal or through the GUI (with or without auto-attach) the error STILL occurs.

What can I do to fix the issue?

**Comment by dorssel** [comment]
Often, devices "reset" themselves after firmware flashing. To the host, this looks like an unplug/replug event. Have a look at the ```--auto-attach``` option. That will continuously try to re-attach the device if it gets detached (e.g., unplugged).

**Comment by dorssel** [comment]
Stale.

It is either fixed by #684, which is in 3.2.0 release, or `--auto-attach` should be used.
