### ISSUE TITLE
Windows client issue

### ISSUE THREAD

**Issue by opensw** [dorssel/usbipd-win#537]
usbipd is working properly with client usbip under Linux. I would like to do the same with a Windows client, I have tried many of them but no one is working, is there any project out there (open source license will be better) that I can use with usbipd? If not, how can I implement my own client under Windows (where can I find info about to communicate via TCP with usbpid)?

Thank you a lot for any help

**Comment by dorssel** [comment]
Duplicate, see https://github.com/dorssel/usbipd-win/issues/65

The USBIP protocol is described in the Linux kernel documentation.
