### ISSUE TITLE
winget installer reboots without prompting...

### ISSUE THREAD

**Issue by ethanhs** [dorssel/usbipd-win#55]
Hi, I am really excited to see this available for the WSL!

I ran the winget installer to install things on my desktop a bit earlier, and was somewhat surprised when my desktop immediately rebooted itself without prompting me. Fortunately I didn't lose any work I had open, and I know drivers require a reboot before working, but I generally expect to be prompted to to reboot now or later.

I would ask/suggest that you either: 
1. prompt the user to reboot now or later or
2. very clearly document this behavior in the README.

Thanks again for the awesome software!

**Comment by dorssel** [comment]
Thanks for the report.

Unfortunately, this is outside the control of the installer.
It is controlled by `winget`, which by default uses silent install (and honors reboot).
This probably can be avoided by using `winget install --interactive`.

Winget issue: https://github.com/microsoft/winget-cli/issues/229

**Comment by ethanhs** [comment]
Ah dang ok, thanks for pointing me to that, perhaps then a warning in the README would be helpful. Kinda surprised that issue is still open over a year later, but I guess figuring out how to fix that is tricky.

**Comment by scyto** [comment]
never rebooted here, did you have some pending updates or something?
