### ISSUE TITLE
Missing folder for MSI build

### ISSUE THREAD

**Issue by RossMcConeghy** [dorssel/usbipd-win#6]
Error when loading the solution (usbipd-win.sln) in VS 2019--
D:\Projects\usbipd-win\Installer\Installer.wixproj : error  : 
The imported project "D:\Projects\usbipd-win\Installer\gitversiontask\5.5.0\build\GitVersionTask.props" was not found. 
Confirm that the expression in the Import declaration "gitversiontask\5.5.0\build\GitVersionTask.props" is correct, and that the file exists on disk.

**Comment by RossMcConeghy** [comment]
Copied from nuGet path to project folder.

**Comment by dorssel** [comment]
Root cause found. We use <PackageReference> in the wixproj file. That is not supported by VS, although it is supported by command line msbuild.
