### ISSUE TITLE
WSL2 + Ubuntu 20.04 + Serial COM PL2303 not associate on  /dev/ttyUSB

### ISSUE THREAD

**Issue by pablitonadal** [dorssel/usbipd-win#618]
hi guys,

My configuration is WSL2 + Ubuntu 20.04

I followed this steps on WIKI WSL support, I tried with "WSL setup" and "wsl-convenience-commands" guide but in both case the result is same. I don't see serial port in /dev/* .

![img1](https://github.com/dorssel/usbipd-win/assets/22638161/aa6b9032-be75-4b19-a409-8ab89f5a1cae)

![img2](https://github.com/dorssel/usbipd-win/assets/22638161/54edbd3e-9398-440d-9eb7-caa733de689b)

![img3](https://github.com/dorssel/usbipd-win/assets/22638161/1a102066-3050-4c8f-9dba-a269d7589fba)

![img4](https://github.com/dorssel/usbipd-win/assets/22638161/ca8505de-5869-4fae-817c-ea4973e01755)

![img5](https://github.com/dorssel/usbipd-win/assets/22638161/858c8c5f-e570-4fd4-933f-4cd10d9dcabb)

![img6](https://github.com/dorssel/usbipd-win/assets/22638161/9ed28d20-8d7c-4f09-b710-b3458c771d47)

**how can I solve this problem?**

Thanks.

**Comment by dorssel** [comment]
Duplicate, with answer here: https://github.com/dorssel/usbipd-win/issues/426#issuecomment-1203257603.

**Comment by dorssel** [comment]
You need to enable the right driver. See: https://www.kernelconfig.io/config_usb_serial_pl2303

**Comment by pablitonadal** [comment]
Thank you very much @dorssel

I followed step by wiki  (https://github.com/dorssel/usbipd-win/wiki/WSL-support) guide and in particular the part "Building your own USB/IP enabled WSL 2 kernel"
When i arrived in step "sudo make menuconfig" I follewed your link instruction that you shared and i had select "USB Prolific 2303 Single Port Serial Driver"

![img8](https://github.com/dorssel/usbipd-win/assets/22638161/3673f5d1-3f98-48c6-85b1-512bc4dd7086)

When I fineshed guide steps I tried share serial com and ubuntu 20.04 it mapped on ttyUSB0

![img9](https://github.com/dorssel/usbipd-win/assets/22638161/17499577-1975-4a6c-99f6-e7e502588d25)

Has worked for me

thanks.
