### ISSUE TITLE
Not able to attach devices using 'attach' 

### ISSUE THREAD

**Issue by Josh23Og** [dorssel/usbipd-win#637]
I recently installed usbipd and followed the instructions but when I try to attach one of the devices using 
`usbipd wsl attach --busid=2-1`
I get the error 
`usbipd: error: WSL 'usbip' client not correctly installed. See https://github.com/dorssel/usbipd-win/wiki/WSL-support for the latest instructions.`
Most of the commands using wsl and usbipd work, it only throws up the error when I try to attach a device

**Comment by dorssel** [comment]
You need to set up the *client* (WSL Linux) side `usbip` tooling properly.

**Comment by base1129** [comment]
I'm encountering the same issue. How do you properly set up the tooling?

**Comment by dorssel** [comment]
What is the error you get when you execute the instructions in the wiki?

**Comment by RBE-Motion** [comment]
I'm having the same exact issue today, trying to attach my USB device

**Comment by dorssel** [comment]
Stale
