### ISSUE TITLE
New Tested Devices

### ISSUE THREAD

**Issue by RedTail72** [dorssel/usbipd-win#660]
I ran some tests with several of my local devices.  Please add these to the [Tested Devices](https://github.com/dorssel/usbipd-win/wiki/Tested-Devices) page.

| Device ID | Description                                       | USB version | Result             | Reason                                            |
|-----------|---------------------------------------------------|-------------|--------------------|---------------------------------------------------|
| 0781:5530 | SanDisk Cruzer                        | 1.1 / 2.0        | :heavy_check_mark: |                                                   |
| 1b1c:1a04 | Corsair Survivor 3.0 | 3.0 | :heavy_check_mark: |                                                   |
| 090c:1000 | Samsung Flash Drive FIT | 3.0 | :heavy_check_mark: |                                                   |
| 14cd:1212 | CanaKit MicroSD Card Reader | 1.1 / 2.0 | :heavy_check_mark: |                                                   |
| 0781:5581 | SanDisk Ultra | 3.0 | :heavy_exclamation_mark: | #659 Device works running in debug mode |
| 0781:5591 | SanDisk Ultra Flair | 3.0 | :heavy_exclamation_mark: | #659 Device works running in debug mode |

**Comment by dorssel** [comment]
Thanks! Will add these as soon as I get back from my trip. Currently traveling, so nothing I can do to test, just replying on phone GitHub app.

**Comment by dorssel** [comment]
Added. Thanks for your contribution!
