### ISSUE TITLE
[wsl] only root can use the usb device (ch340 serial in this case).

### ISSUE THREAD

**Issue by wzqvip** [dorssel/usbipd-win#681]
I just mount CH340 Serial USB to wsl2 (`Linux Taco-Studio 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`). 
But when I access the /dev/ttyUSB0, it says `/dev/ttyUSB0 is currently open. Please close any other terminal programs that may be using /dev/ttyUSB0 and try again.`

Only when I use root it is fine. So I looked up by ` stat /dev/ttyUSB0`, and it's Gid is root. So only root users can access it.
I'm not sure what has caused this. But on an native Linux machine, normal user can access the CH340 device. 

mounting the device from windows to wsl needs admin privilege, i"m not sure if this is just fine. 
<img width="734" alt="image" src="https://github.com/dorssel/usbipd-win/assets/30136639/faf4888a-4648-461a-9527-ead7d21f0098">

I can just use root to access to the serial port, but it is risky and annoying (different environment).

<img width="523" alt="image" src="https://github.com/dorssel/usbipd-win/assets/30136639/9c10862f-1d0b-40b9-9016-d8d98474aa1e">

**Comment by dorssel** [comment]
You probably have to restart `udev` after attach. Depends on your WSL version and /or distro. Look through the other issues; it has been solved before. This is a WSL issue, not `usbipd-win`.
