### ISSUE TITLE
Unclear WSL2 Instructions

### ISSUE THREAD

**Issue by johnaweiss** [dorssel/usbipd-win#686]
These instructions in the readme seem contradictory:

> **WSL 2
> You can use the usbipd wsl subcommand to share and connect a device with a single command.** 
> ...
> **As a workaround, instructions on how to setup a USBIP client for WSL 2 can be found on the wiki.**

Why do i need a "workaround" when you provide the "single command" to do the same thing?

**Comment by dorssel** [comment]
You're confusing `usbipd` (server side, Windows) with `usbip` (client side, WSL).

The statements aren't contradictory, but rather complementary. You really need both.

**Comment by johnaweiss** [comment]
Ok, thanks for the clarification.
