### ISSUE TITLE
bzImage not found while Building your own USB/IP enabled WSL 2 kernel

### ISSUE THREAD

**Issue by aleksandr-vin** [dorssel/usbipd-win#728]
I'm following the guide https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools

and at the line
```
cp arch/x86/boot/bzImage /mnt/c/Users/<user>/usbip-bzImage
```
There is no such file in arch/x86/boot dir.

**Comment by dorssel** [comment]
You're not providing a lot of information. See older issues on what others did to resolve their problem (and hints on providing some more feedback): https://github.com/dorssel/usbipd-win/issues?q=is%3Aissue+bzImage+is%3Aclosed
