### ISSUE TITLE
can't attach device from WSL

### ISSUE THREAD

**Issue by ZZH-Finzlize** [dorssel/usbipd-win#752]
When I use command `usbip list -r 192.168.1.3`, I found it can list the devices that bind with usbipd-win, but I can't use `usbip attach -r 192.168.1.3 -b 4-2` to attach this device to WSL. Why is that? I think the connection should be able to build from both side (from Windows or from WSL)

![image](https://github.com/dorssel/usbipd-win/assets/33342565/6714353a-987e-480d-bb14-3dab0beefbb8)

![image](https://github.com/dorssel/usbipd-win/assets/33342565/f58958fe-f544-4a12-b504-e64738a4c010)

**Comment by dhcstruggle** [comment]
Same issue here.

**Comment by ZZH-Finzlize** [comment]
> I found solution here and it works for me. just FYI: [#663 (comment)](https://github.com/dorssel/usbipd-win/issues/663#issuecomment-1683761470)

It is different than my issue, because I can build the connection from Windows use `usbipd wsl attach` command, this command works well, but what I want is build this connection from WSL by `usbip attach` command, and this command will report "Device busy". 

Still thx for that.

**Comment by dorssel** [comment]
"Device busy" means that the host is currently actively using the device. Either stop the software/service on Windows that is using the device, or use `usbipd bind --force`.

**Comment by ZZH-Finzlize** [comment]
> "Device busy" means that the host is currently actively using the device. Either stop the software/service on Windows that is using the device, or use `usbipd bind --force`.

@dorssel Actually, That device is already bind to usbipd with the --force flag, but it just can't attach from WSL (from Windows is OK), and I find if I change `networkingMode` to `mirrored`, then I can attach the same device from WSL, meanwhile, from Windows to attach the device will fail.

![image](https://github.com/dorssel/usbipd-win/assets/33342565/0c80047a-f492-4c53-9296-e15c689231dc)

.wslconfig
![image](https://github.com/dorssel/usbipd-win/assets/33342565/7676f89b-a519-4a1f-a98f-75444e46fa6f)

**Comment by ZZH-Finzlize** [comment]
> "Device busy" means that the host is currently actively using the device. Either stop the software/service on Windows that is using the device, or use `usbipd bind --force`.

I guess I find the reason, attach a device from WSL has to be under the root privilege, if execute the `usbip` command without `sudo`, even chang the .wslconfig is useless.

**Comment by dorssel** [comment]
> attach a device from WSL has to be under the root privilege

That is correct, and that is what `usbipd wsl attach` uses underwater. mirror mode is not yet supported, see https://github.com/dorssel/usbipd-win/issues/714. Is your issue resolved now?

**Comment by ZZH-Finzlize** [comment]
> > attach a device from WSL has to be under the root privilege
> 
> That is correct, and that is what `usbipd wsl attach` uses underwater. mirror mode is not yet supported, see #714. Is your issue resolved now?

Yes, Thanks for the help.
