### ISSUE TITLE
Unable to attach device with fresh version of WSL2 - Ubuntu 22

### ISSUE THREAD

**Issue by Leiyks** [dorssel/usbipd-win#787]
Hi all !

I recently switched to WSL and I am trying to connect my USB component to WSL by following the [guide](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) provided by Microsoft.
(I tried everything on the a fresh WSL install, so the only command that have been run before following the guide was `sudo apt update && sudo apt upgrade`)

However when trying to actually attach **any** of my devices I get:

```
$ usbipd wsl attach --busid 4-1
usbip: error: Attach Request for 4-1 failed - Device busy (exported)

usbipd: error: Failed to attach device with BUSID '4-1'.
```

I searched for a solution and tried a bunch of things, such as:

- Trying with version 3.0 of usbipd-win and same instructiuons
- Trying with version 2.0 of usbipd-win with instructions of this wiki
- Trying multiple other installation commands I saw on issues/stackoverflow/etc... (linux-tools-virtual, etc...)

What is odd is that in every cases after running the attach command, I tried other commands and got this:

```
$ usbipd wsl list
BUSID  DEVICE                                                        STATE
...
4-1    USB Input Device, Microsoft Usbccid Smartcard Reader (WUDF)   Not attached
...
```

```
$ usbipd list
Connected:
BUSID  DEVICE                                                        STATE
...
4-1    USB Input Device, Microsoft Usbccid Smartcard Reader (WUDF)   Shared
...

Persisted:
GUID                                  DEVICE
```

So even though the attach command did not work, the device appear as Shared only when not using the WSL commands subset.

Can you please help me figure out what I am missing in all this ?

**Comment by dorssel** [comment]
Duplicate, see https://github.com/dorssel/usbipd-win/issues/752#issuecomment-1798281981
