### ISSUE TITLE
WSL can't list 

### ISSUE THREAD

**Issue by stoffej** [dorssel/usbipd-win#806]
Running on Win11
![image](https://github.com/dorssel/usbipd-win/assets/2614910/b374ca69-3b99-4ae0-8c10-f850a0dfa988)

Cant list the devices in windows.(tried both ip:s)
![image](https://github.com/dorssel/usbipd-win/assets/2614910/9e4be6eb-3436-4f8f-a3a6-2312ed150402)
The ip is pingable from wsl, and port is open.
Works with open a server on 3240 and connect to it using telnet on the same port.

Usbipd in debug mode.
![image](https://github.com/dorssel/usbipd-win/assets/2614910/f7f36ad3-2866-43c3-ab10-31ee0875f4e2)

**Comment by dorssel** [comment]
What distro are you using and what's the output of `usbip version`.

**Comment by stoffej** [comment]
![image](https://github.com/dorssel/usbipd-win/assets/2614910/a3e8adba-88d1-4131-a6f4-0b7bb1c7459b)
![image](https://github.com/dorssel/usbipd-win/assets/2614910/cabce62f-8931-447e-8390-b5e894d6d786)
![image](https://github.com/dorssel/usbipd-win/assets/2614910/431f1072-946e-4db4-845c-8b556f7c9f1f)
![image](https://github.com/dorssel/usbipd-win/assets/2614910/0b464ca6-ee6f-45f9-a6d1-72fdbfdd9c07)

It works on my colleagues computer. But not mine. And no traffic is generated from the "usbip list ..."
Can something with the network settings block this?
Firewall in windows is disabled

**Comment by dorssel** [comment]
What `usbip` client package is installed? What is the distribution? Since 4.0.0, `usbipd-win` ships its own `usbip` client tools. What happens if you simply do `usbipd attach --wsl` on the Windows side?

**Comment by stoffej** [comment]
Thanks for the quick reply.
How do find info about this? "What usbip client package is installed? "
![image](https://github.com/dorssel/usbipd-win/assets/2614910/be4f1348-5b6b-47eb-8410-b3083b789f56)
The distrubution is
![image](https://github.com/dorssel/usbipd-win/assets/2614910/f6df5538-a1c4-4489-b623-c07da8778305)

**Comment by dorssel** [comment]
OK, so it is not `usbip`, that is OK. And it is not the `usbipd` service (as that would have given a warning too). The connection between WSL and the service is also working properly, as that is checked before the attach itself is even attempted.

All that remains is that Windows is not able to change the driver "on-the-fly". Try binding the device with `usbipd bind --force`.

**Comment by stoffej** [comment]
Yes , but ping works and I can manually create a server on port 3240 on windows and connect to it from wsl.
Leaning to reinstall windows due to some hickup with network, but thats the last resort. Wanted to check with you if it could be something with uspipd <-> usbip first.

**Comment by dorssel** [comment]
In the past I've seen issues with the version of `usbip` client tooling. Until 4.0.0 it was difficult to get the right client tools installed. However, your distro is modern (22.04), so that isn't it. I suggest you try to do a repair install or reinstall of `usbipd-win` first.

**Comment by stoffej** [comment]
I have tried that and, is there a special usbip that is installed ?

**Comment by dorssel** [comment]
It is installed on the Windows side, and it is used within WSL as `/mnt/c/Program Files/usbipd-win/wsl/usbip`.

**Comment by dorssel** [comment]
4.1.0 has improved WSL support, could you try that?

**Comment by stoffej** [comment]
I reinstalled my pc and now usbipd works again.
So something else was preventing it to work.
Suggest that this Issue shall be closed
