### ISSUE TITLE
Device disconnects after attach (Updated to USBIPD V4.0.0)

### ISSUE THREAD

**Issue by jesgarmar** [dorssel/usbipd-win#808]
Hello,

I've updated to the newest version of usbipd. I'm binding a device (RealSense camera) and when i try to attach to my WSL, the device disconnects and there is an error msg:
"usbipd: error: Failed to attach device). The "usb unplug sound" occurs and then the device is no longer detected in windows.

I was working with the older version but its not longer working. I'm attaching a picture and i can provide more information if needed. 

PD: The camera was working till last update of usbipd and i've updated the wsl with "wsl --update".

Thanks
![error_usbipd_v4 0 0](https://github.com/dorssel/usbipd-win/assets/50942087/325c4074-73f6-41d1-ab58-1bb5c56c5bc4)

**Comment by dorssel** [comment]
The version of WSL is not important here. This problem arises from the driver switch (Windows-side) that needs to happen at the time of attach. It depends on whether the device is (or was) in use by Windows. This functionality hasn't changed between 3.2.0 and 4.0.0, but the included VirtualBox drivers were updated (which may be the cause). If it doesn't work after reboot (the usual Windows solution for almost everything), you may have to bind the device using `--force`.

**Comment by jesgarmar** [comment]
> The version of WSL is not important here. This problem arises from the driver switch (Windows-side) that needs to happen at the time of attach. It depends on whether the device is (or was) in use by Windows. This functionality hasn't changed between 3.2.0 and 4.0.0, but the included VirtualBox drivers were updated (which may be the cause). If it doesn't work after reboot (the usual Windows solution for almost everything), you may have to bind the device using `--force`.

It worked after binding with '--force' param. Thanks!
