### ISSUE TITLE
Is there a usbip client for windows? That I can share use devices across two windows PC by network.

### ISSUE THREAD

**Issue by joshuafc** [dorssel/usbipd-win#813]
Good job!
But, Is there a usbip client for windows?
I want to share USB Devices between two windows computer.

**Comment by joshuafc** [comment]
![企业微信截图_170350971286](https://github.com/dorssel/usbipd-win/assets/7185089/3977f71a-7242-410c-aca5-fea077e94e95)

**Comment by dorssel** [comment]
No, sorry, see README and a dozen earlier questions with reply.
