### ISSUE TITLE
how to install and use with wsl centos 9

### ISSUE THREAD

**Issue by lokize** [dorssel/usbipd-win#828]
is there any way to use with centos9 and wsl2?

**Comment by dorssel** [comment]
As far as I know, nothing special. Just install and go.
Have you tried? What is not working?

**Comment by lokize** [comment]
i attached my webcam in powershell to wsl, how to see this device in wsl? i tried using in android studio but i think not worked because i have a error "can't start camera"

![image](https://github.com/dorssel/usbipd-win/assets/19701630/833e3187-596b-4dec-abb2-044dc5082b02)

![image](https://github.com/dorssel/usbipd-win/assets/19701630/6ee57ab2-cd0b-4073-a5ec-f9af7f2ef59e)
