### ISSUE TITLE
Unverified Primary Signature and Checksum Mismatch on Drivers

### ISSUE THREAD

**Issue by Snausage0x45** [dorssel/usbipd-win#829]
Both VBoxUsb.sys and VBoxUsbMon.sys have a primary cert which was initially used to sign the files in 2014 (spoofing possibly aside) by a certificate issued to Oracle from Verisign,  which has not been revoked, however there are some discrepancies with the cert and it's countersigner.

Looking at VboxUsbMon.sys it was compilied in 2023

<img width="242" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/83ef39c2-82a0-4df2-87bc-e57b7426d85d">

Yet the primary cert, serial 51ca009816fdbd80f120e015ee75823e, is timestamped to 2014, fails signtool verification and was only valid until Dec, 2016

<img width="299" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/efc93b12-2a31-416b-9a49-15b12f4c6a8d">

<img width="605" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/95fa94c9-7c8c-4190-bf3b-db4b0c496c93">

with the countersigner certificate being issued by a CA which could not be verified

<img width="906" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/41f595e1-9b89-498c-add0-e3ac07ef737c">

The cert was issued to VirtualBox for Legacy Windows Only Timestamp Kludge 2014 by VirtualBox for Legacy Windows Only Timestamp CA which could not be found

<img width="298" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/8103e1c7-e4a4-40a8-b3e9-36bfc1e0ff7f">

signtool output:

<img width="526" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/de1acced-0db3-43a7-9719-6b7930a7d372">

After initial signing the file appears to have been modified due to a mismatch in the checksums

<img width="335" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/290f1c9a-2ca4-49b7-b174-f9b01f90e35e">

It was then later signed in October 2023 first by an Oracle certificate then by Microsoft Window's Hardware Compatibility cert based on signing times

The second Oracle signing cert also has an issue of an untrusted root CA being used in the cert path

<img width="402" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/255ae90d-16d4-447f-a63c-322df8d16b7b">

The included cat files only validate the last signature applied from Microsoft 

<img width="447" alt="image" src="https://github.com/dorssel/usbipd-win/assets/38758896/bf0c5bba-4127-415a-85be-9718e074b100">

Given tools like HookSignTool and FuckCertVerifyTimeValidity, the initial timestamp being 2015 or before, plus the other discrepancies, just for posterity's sake could you validate that: 
* This is expected,
* The reason for the hashsum mismatch,
* The process of getting the drivers from Oracle to being uploaded to the repo

**Comment by dorssel** [comment]
Yes, this is all known. And not a problem, since the drivers are validly signed with a Microsoft attestation signature (i.e., Windows 10+ uses the sha256 signature and allows for additional (even non-valid) signatures), as long as the attestation signature chain is correct.
Oracle has its historical reasons (XP/Vista support, mainly), which `usbipd-win` does not use/rely on.
What is your issue with `usbipd-win`?

**Comment by Snausage0x45** [comment]
Yeah you're right looks like the issue is on the Oracle side, they're doing some interesting things. Though, the WHQL process is far from fool proof and has been abused in the past to sign malicious drivers so just the presence of the WHQL signature is not the panacea msft wishes it were. The fact there is a checksum mismatch on the first signature and that its back-dated to 2014, which is part of a way to abuse a loophole in the driver verification policy, plus the root CA issues on the second signature is at least out of the ordinary if nothing else.
