### ISSUE TITLE
My xbox 360 controller is not working anymore after unbind 

### ISSUE THREAD

**Issue by vitoo** [dorssel/usbipd-win#838]
Hello,

i tried to redirect my xbox controller from a windows (usbipd-win as server ) to windows  ([usbip-win2](https://github.com/vadimgrn/usbip-win2) as client)

it worked one time, but after unbinding the controller from the server, and unplug/replug, it's not recognized anymore by windows 

is there a device i should delete in the device manage ? 
but nothing appear as my xbox controller so i don'tk now what to do 

Thanks for your help

**Comment by Katashynskyi** [comment]
hi @vitoo, I'd like to ask, your controller displays in wsl2 in some local file explorer like nautilus as a device?

**Comment by vitoo** [comment]
i don't have wsl, but on debian (usb over ip, or local usb) i can see it with the command : `lsusb` or  `dmesg`
