### ISSUE TITLE
Attaching external usb to Docker container 

### ISSUE THREAD

**Issue by vocaldrain** [dorssel/usbipd-win#850]
I'm running docker desktop through WSL. It is possible to attach external usb device to container through this?

OS Name:  Microsoft Windows 11 
Version	10.0.22631 

I've external Wi-Fi adapter and want it to connect running Linux container.

**Comment by dorssel** [comment]
Yes, `usbipd-win` works with docker as well. However, the default WSL kernel does not have WiFi (or any USB network) drivers, so you will have to build your own, see https://github.com/dorssel/usbipd-win/wiki/WSL-support#building-your-own-wsl-2-kernel-with-additional-drivers.
