### ISSUE TITLE
The "wsl" is not listing on my commands

### ISSUE THREAD

**Issue by kdeligiorgis** [dorssel/usbipd-win#857]
Hi all, 

I am trying to set up usbipd with WSL on Windows 10. 
After the installation, when I list the commands, the wsl does not appear.

![Screenshot 2024-02-07 115841](https://github.com/dorssel/usbipd-win/assets/85018183/c94bcf5f-7bba-4a4e-9118-26da9151a33e)

**Comment by dorssel** [comment]
That's because it no longer exists. See the README for the new syntax (hint: try `usbipd attach`).
