### ISSUE TITLE
Unable to install usbipd

### ISSUE THREAD

**Issue by hmmm23e435** [dorssel/usbipd-win#871]
<img width="509" alt="csse3010" src="https://github.com/dorssel/usbipd-win/assets/160568242/7265c9a6-d878-4e0f-83a9-9a3bc42bb9e2">

<img width="645" alt="image" src="https://github.com/dorssel/usbipd-win/assets/160568242/9b4f7e9b-1d97-48fa-a700-3d6b4b244c8c">

**Comment by dorssel** [comment]
Did the `winget` install complete? Did you restart PowerShell to pick up the new PATH?

**Comment by dorssel** [comment]
stale
