### ISSUE TITLE
vhci -> xhci 

### ISSUE THREAD

**Issue by beni20** [dorssel/usbipd-win#872]
hi 
any clue if i could somehow swap the driver vhci -> xhci ?
i have some odd USB BT card which needs to load some firmware onto the device during init and looks like something strange is happening. I guess issue is with vhci.
With vmware it works but there is xhci 
What happens if i try to swap vhci to xhci after attachment? will passthrough/hardware still work? 

any tips/recommendations?:)

**Comment by dorssel** [comment]
That's not related to `usbipd-win`, which is server side USBIPD. vhci/xhci is a client side issue.
