### ISSUE TITLE
usbipd-win for HyperV guests

### ISSUE THREAD

**Issue by arijith96** [dorssel/usbipd-win#877]
The README.md says that we can use the usbdip with HyperV guests too.
I wanted to reconfirm if this is already implemented, such that I can connect to a local USB device from within a Windows VM that is running on the HyperV.

The unclarity arose from this:
![image](https://github.com/dorssel/usbipd-win/assets/35350917/89491f1a-7918-4079-9c6a-724c44b38fb1)

**Comment by dorssel** [comment]
README also says:

> Client-side tooling exists for other operating systems such as Microsoft Windows, but not as part of this project.

Duplicate of https://github.com/dorssel/usbipd-win/issues/813
