### ISSUE TITLE
binding works but /dev/tty* not created anymore

### ISSUE THREAD

**Issue by proddy** [dorssel/usbipd-win#888]
I have one of those annoying issues where it used to work forever (great software btw), and now suddenly, it doesn't. And I'm not sure what's changed.

usbipd-win 4.1.1

```
PS C:\Users\paul> usbipd list
Connected:
BUSID  VID:PID    DEVICE                                                        STATE
1-6    1a86:7523  USB-SERIAL CH340 (COM4)                                       Not shared

PS C:\Users\paul> usbipd bind -b 1-6
PS C:\Users\paul> usbipd attach  -w -b 1-6
usbipd: info: Using WSL distribution 'Ubuntu' to attach; the device will be available in all WSL 2 distributions.
usbipd: info: Using IP address 172.18.64.1 to reach the host.
```
and in WSL it used to created a `/dev/ttyUSB0` but not anymore. It may have been after a Windows update or an Ubuntu apt update, or too much wine. Can't remember!

The log shows:
```
info: Usbipd.ConnectedClient[1]
      Client 172.18.68.123 claimed device at 1-6 (USB\VID_1A86&PID_7523\8&384B90AF&0&6).
```

Permissions and mount points all look fine. Tried version 4.1.0 too. 

Any ideas?

**Comment by proddy** [comment]
I just built a new WSL using `wsl --install -d Ubuntu-22.04` and it works there fine, so I think I must have added/removed something from the previous distro that messed it up. Then I did ` sudo update-alternatives --install /usr/local/bin/usbip usbip /usr/lib/linux-tools/*/usbip 20` on the old WSL distro that wasn't worked and now that one works. ffs. So better not touch it.

**Comment by proddy** [comment]
Problem came back - I rebuilt the WSL to fix it. Still unsure of what caused it.

**Comment by dorssel** [comment]
As I Understand it, attaching the device to WSL itself works. This means the problem is with WSL , not with `usbipd-win`. Maybe you can get help at https://github.com/microsoft/WSL/issues.
