### ISSUE TITLE
usbipd wsl yubikey can't input to terminal

### ISSUE THREAD

**Issue by ezeutno** [dorssel/usbipd-win#90]
I been trying to use the usbipd which a great tool to bridge between wsl and my yubikey. I found an issue, is that I don't know where the usbipd yubikey give the input when I touch the yubikey for the access token. Thank you in advance.

**Comment by dorssel** [comment]
It enters it as keystrokes on the keyboard it emulates. So those will end up on the console. WSL instances don't really have a console. But you can get the input from

```
sudo cat /dev/console
```

**Comment by ezeutno** [comment]
Okay.. thanks ... That means more work around but okay.
