### ISSUE TITLE
Feature request: persistant system service to automatically bind based on PID / VID / serial number / device class ... 

### ISSUE THREAD

**Issue by christophmuellerorg** [dorssel/usbipd-win#904]
First of all: thanks for your work, the tool is amazing and extremely useful as it allows us to port a linux flow for an embedded device to windows without having to deal with switching drivers to libusb. 

What I would love to see would be the ability to bind USB devices based on a whitelist, independent of the USB port the device is connected to. I am aware that the current setup using the busid is a limitation of the windows USB subsystem. However, I have users which do not have admin permissions and it would be nice to have USB devices automatically bound as required. The USB ports where a device will be connected to cannot be anticipated (think of USB hubs or screens with built in docking stations) and the devices in question are not necessarily at hand or connected when the system is set up.

I believe this functionality could be implemented with usbipd-win running as a system service with elevated permissions, listening to USB connect events and comparing the USB device against a white list binding devices on the fly. The whitelist could allow for entries based on any combination of product id, vendor id, serial number, or device class, similar to what is possible with udev rules in linux.

**Comment by dorssel** [comment]
This is something I've been thinking about a lot. Some sort of authorization system. It is somewhat complex and security is a difficult issue with the embedded VirtualBox drivers to begin with...

See also https://github.com/dorssel/usbipd-win/discussions/774#discussioncomment-7648135.

Yes ... I *will* start a discussion on this soon, so we can make a proper design. It's not going to be a quick hack, but a proper solution. Feel free to join in once this gets on the way. It has been on my own wish list as well. Thanks for the report!

**Comment by dorssel** [comment]
See https://github.com/dorssel/usbipd-win/discussions/910

**Comment by dorssel** [comment]
Feature has been merged into master branch.
