### ISSUE TITLE
Mounting within WSL failed

### ISSUE THREAD

**Issue by arkaw2222** [dorssel/usbipd-win#917]
Hi there! Could you help please.. 
trying to attach sd-card to wsl, but it gives error:
usbipd: error: Mounting 'C:\Program Files\usbipd-win\WSL' within WSL failed.

WSL 2, usbipd 4.1.0, linux distribution fedora

P.s. sorry for my lang, im russian, dont know eng as good as u :(
![image](https://github.com/dorssel/usbipd-win/assets/166355084/fd4100a7-4f80-49cc-ba3b-641a672f91bd)

**Comment by dorssel** [comment]
This is a known problem for some distributions (apparently including fedora). It has been fixed in the master branch. Please use the installer from the latest master branch: https://github.com/dorssel/usbipd-win/actions/runs/8581245579.

**Comment by arkaw2222** [comment]
Thanks a lot, but i can see there only build-installer.yml, please guide me how to install dev build, kind man :)

**Comment by dorssel** [comment]
Just below it says "Artifacts" and "msi-installer". Download ... unzip ... install.

**Comment by arkaw2222** [comment]
> Just below it says "Artifacts" and "msi-installer". Download ... unzip ... install.

I found elder discussion, the same problem, but i could download dev installer, now i understood im a bit blind :)
Thanks, issue solved 👍
