### ISSUE TITLE
connecting devices over 3 machines

### ISSUE THREAD

**Issue by Mark62222** [dorssel/usbipd-win#919]
Hi i was just wondering if its possible to connect a device with usbipd to another device and then from that device to another, i have tried this and it doesn't seem to work but just wanted to know if it was possible.

Thanks

**Comment by dorssel** [comment]
I think that should work (I see no reason why it shouldn't), but I've never tried it.

**Comment by Mark62222** [comment]
so when i connect a device and then on the device i connected it to do a usbip list -l its dosent show but lsusb it does

**Comment by Mark62222** [comment]
Sorry for any confusing, what you described is what I'm trying to do, but when the phone is attached to the client on that client i cannot see the device busid using usbip as the phone doesn't, which means I cant bind it again in order to connect it again to the next client machine.

**Comment by dorssel** [comment]
Hmm, apparently the Linux kernel doesn't like it. I get:

```
usbip: error: bind loop detected: device: /devices/platform/vhci_hcd.0/usb1/1-1 is attached to vhci_hcd
```

So, it looks like it is not possible...

**Comment by Mark62222** [comment]
Ok thanks.

**Comment by dorssel** [comment]
Not an usbipd-win issue.
