### ISSUE TITLE
When is 4.1.1 with mount issue release as a signed installer?

### ISSUE THREAD

**Issue by Redfire1234au** [dorssel/usbipd-win#928]
Hi 

I tried to install the unsigned installer (https://github.com/dorssel/usbipd-win/pull/859) and it got flagged by Coretex XDR as WildFire

![Screenshot 2024-04-26 120630](https://github.com/dorssel/usbipd-win/assets/168094677/d9b54db9-deac-4cc7-8b43-179645b977c7)

The 4.1.0 didn't get flagged / quarantined. Any chance of a signed package soon?

Cheers

**Comment by dorssel** [comment]
Soon(TM)

**Comment by Redfire1234au** [comment]
Thank you so very much!
