### ISSUE TITLE
could you possibly release a signed usbip client for win?

### ISSUE THREAD

**Issue by ashleyw-gh** [dorssel/usbipd-win#930]
hi, love your work!
Is it possible for you to release a signed usbip client to go along with your server process for x64 windows?
Whats missing from all the other forks seems to be signed drivers/binaries, which make it increasing difficult to use on most machines.
It would great if you could release a signed 64 bit windows client driver to go along with your binary (as it looks like the daemon process has already been signed).
thanks a million!

**Comment by dorssel** [comment]
Client side is outside the scope of this project. For reasons, see other issues that mentioned this.
