### ISSUE TITLE
Permissions - solved

### ISSUE THREAD

**Issue by dzid26** [dorssel/usbipd-win#964]
Initial [issue](https://gitlab.com/alelec/wsl-usb-gui/-/issues/27).

After device was visible in `lsusb` (wsl ubuntu 20.04), I was struggling to do anything else. 
```
 lsusb -v  | grep panda
can't get debug descriptor: Resource temporarily unavailable
```

I also tried `sudo usermod -a -G plugdev {user}`

Last command that finally made it work [was](https://github.com/FreeRDP/FreeRDP/issues/6651#issuecomment-741564663):
` sudo chmod -R 777 /dev/bus/usb/`

**Comment by dorssel** [comment]
You solved an issue reported in another project, and now you *open* an issue here. What am I missing?

**Comment by dzid26** [comment]
Sorry for confusion.
I just wanted to leave a trace for others of a possible solution.
