### ISSUE TITLE
Connecting a Intel RealSense Depth Camera D415

### ISSUE THREAD

**Issue by Mokaz** [dorssel/usbipd-win#983]
I'm trying to connect a RealSense D415 Depth Camera, but it does not attach correctly. I have tried using bind with `--force`, but it still does not show up in WSL when using `lsusb`
![image](https://github.com/dorssel/usbipd-win/assets/25727569/ef503cef-6e4c-42c8-ad4d-79c9bedab2d2)

Running `usbipd attach --wsl --busid 2-17`:
![image](https://github.com/dorssel/usbipd-win/assets/25727569/7bdc3463-7073-4fa9-8e38-7637807dd493)

Firewall rule inbound:
![image](https://github.com/dorssel/usbipd-win/assets/25727569/fc2246a3-0b4c-4aa2-b314-72530061ce26)

Firewall rule outbound:
![image](https://github.com/dorssel/usbipd-win/assets/25727569/ca381945-22b3-4c59-b71b-ecba6711b256)

I'm running Ubuntu 22.04.4 LTS

**Comment by dorssel** [comment]
What is the version of usbipd-win? And of your Windows host?

**Comment by Mokaz** [comment]
usbipd-win 4.2.0 and Windows 11 Pro 23H2 22631.3737

**Comment by dorssel** [comment]
Are you using 'networkingMode=mirrored' or the default bridged mode?

**Comment by Mokaz** [comment]
Default bridged mode. I haven't changed any settings.

**Comment by dorssel** [comment]
Are you using any third party security software? Something seems to be blocking the network connection from WSL back to the host.

**Comment by Mokaz** [comment]
Well yes, that could very well be the problem. I'm using a work pc, and there are IT security programs installed. I'll contact IT and ask about it. If unblocking the ports is not an option, do you have any other suggestions for connecting the camera to WSL?

**Comment by dorssel** [comment]
You can use an `ssh` reverse tunnel. Look through older (possible closed) issues about this subject.

**Comment by Mokaz** [comment]
Turns out company IT policy was blocking usbipd. After removing restrictions the device attaches fine, and shows up WSL using lsusb. However, it is not detected by Intel Realsense viewer.
