### ISSUE TITLE
usbipd not being recognised as command or executable

### ISSUE THREAD

**Issue by Deus-Ex-Machina2** [dorssel/usbipd-win#990]
I am knew to embedded systems and I am unsure why I cannot use this software. I keep getting the following error:

usbipd list

usbipd : The term 'usbipd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

At line:1 char:1
+ usbipd list
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (usbipd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
My path environment variable is C:\Program Files\usbipd-win\

Please could someone assist, as I do not know what is wrong.

**Comment by dorssel** [comment]
what is the output of `dir "C:\Program Files\usbipd-win"` ?

**Comment by Deus-Ex-Machina2** [comment]
> what is the output of `dir "C:\Program Files\usbipd-win"` ?

Hi dorssel, I end-up using the .msi file again to do repairs. So the problem is solved now. Thanks for getting back to me though.
