### ISSUE TITLE
`WSL kernel is not USBIP capable` with WSL pre-release 2.3.11

### ISSUE THREAD

**Issue by polyzen** [dorssel/usbipd-win#995]
I can't seem to find anything matching `vhci` nor `usbip` under `/sys`. Not sure if there's some place else to check with Linux 6.x or what.

~~`sudo usbip list --remote=$IP` results in `usbip: error: could not connect to $IP:3240: System error`~~ Edit: Apparently irrelevant

Distro is Arch Linux.

Edit: Just to note I tried both the latest release and the dev build.

**Comment by dorssel** [comment]
On your WSL instance, what is the output of `cat /sys/devices/platform/vhci_hcd.0/status`?

**Comment by polyzen** [comment]
On July 17, 2024 7:28:12 PM EDT, Frans van Dorsselaer ***@***.***> wrote:
> On your WSL instance, what is the output of `cat /sys/devices/platform/vhci_hcd.0/status`?
> 

That directory does not exist.

--
Best,
Daniel <https://danielcapella.com>

**Comment by dorssel** [comment]
What is the output of `zgrep CONFIG_USBIP /proc/config.gz`?

**Comment by polyzen** [comment]
<details>
  <summary>show/hide</summary>
  <p>

```
CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1
CONFIG_USBIP_HOST=m
# CONFIG_USBIP_DEBUG is not set
```
  </p>
</details>

**Comment by dorssel** [comment]
Ah, they modularized it! (`=m`); this used to be monolithically built-in (`=y`).
You need to load the module first: `sudo modprobe vhci-hcd`.

**Comment by polyzen** [comment]
Works now :D

**Comment by polyzen** [comment]
https://wiki.archlinux.org/title/Kernel_module#systemd docs for automatic module loading

Should I leave this open until this is documented or something?

**Comment by dorssel** [comment]
No, but I would report this to https://github.com/microsoft/WSL/issues. I don't think it is intended. But if it is, we would like to know that too. It has happened in the past that they inadvertently put some config settings to "module", whereas the WSL kernel (at least until now) is supposed to be entirely monolithic.

**Comment by dorssel** [comment]
BTW: it worthwhile noting thay `CONFIG_USBIP_HOST=m` makes absolutely no sense. It used to be `# CONFIG_USBIP_HOST is not set`. WSL can never be a USB host. There is no physical USB, and the Linux USBIP subsystem does not allow forwarding client USB devices.

**Comment by polyzen** [comment]
https://github.com/microsoft/WSL/issues/11792

**Comment by dorssel** [comment]
From the release notes it appears they *are* going the modularized way... No definitive answer yet, see https://github.com/microsoft/WSL/discussions/11789#discussioncomment-10083621

In the meanwhile, I've attempted supporting it, see #996.

Could you give the development installer a try? It is at https://github.com/dorssel/usbipd-win/actions/runs/9997393400?pr=996

Please test:
- clean WSL boot (`wsl --shutdown` first)
- without loading the module manually: `usbipd attach --wsl`
- `usbipd detach`
- while the module is already loaded: `usbipd attach --wsl`

Please post the console output. Thx.

**Comment by polyzen** [comment]
```
~ > usbipd.exe attach --wsl --hardware-id '$hwid'
usbipd: info: Device with hardware-id '$hwid' found at busid '$busid'.
usbipd: info: Using WSL distribution 'Arch' to attach; the device will be available in all WSL 2 distributions.
usbipd: info: Loading vhci_hcd module.
usbipd: info: Using IP address $ip to reach the host.
~ > usbipd.exe detach --hardware-id '$hwid'
usbipd: info: Device with hardware-id '$hwid' found at busid '$busid'.
~ > usbipd.exe attach --wsl --hardware-id '$hwid'
usbipd: info: Device with hardware-id '$hwid' found at busid '$busid'.
usbipd: info: Using WSL distribution 'Arch' to attach; the device will be available in all WSL 2 distributions.
usbipd: info: Using IP address $ip to reach the host.

**Comment by dorssel** [comment]
@polyzen 
Awesome, thx. I'm merging this, which will (once again) close this ticket. Thanks for the input!

**Comment by tyeth** [comment]
> BTW: it worthwhile noting thay `CONFIG_USBIP_HOST=m` makes absolutely no sense. It used to be `# CONFIG_USBIP_HOST is not set`. WSL can never be a USB host. There is no physical USB, and the Linux USBIP subsystem does not allow forwarding client USB devices.

@dorssel Does it make sense if I want to forward usbip connections from an rpi-zero2w to wsl, along with wslg running firefox nightly in wsl to test web-serial using the usbip connections?

I'm experiencing this error calling usbip:
```
tyeth@framework16:/mnt/c/Users/tyeth$ cat /sys/devices/platform/vhci_hcd.0/status
cat: /sys/devices/platform/vhci_hcd.0/status: No such file or directory
tyeth@framework16:/mnt/c/Users/tyeth$ zgrep CONFIG_USBIP /proc/config.gz
CONFIG_USBIP_CORE=m
CONFIG_USBIP_VHCI_HCD=m
CONFIG_USBIP_VHCI_HC_PORTS=8
CONFIG_USBIP_VHCI_NR_HCS=1
CONFIG_USBIP_HOST=m
# CONFIG_USBIP_DEBUG is not set
tyeth@framework16:/mnt/c/Users/tyeth$ sudo modprobe vhci-hcd
[sudo] password for tyeth:
tyeth@framework16:/mnt/c/Users/tyeth$ exit
logout
PS C:\Users\tyeth> wsl --version
WSL version: 2.6.3.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26200.8246
PS C:\Users\tyeth> wsl
tyeth@framework16:/mnt/c/Users/tyeth$ usbip
WARNING: usbip not found for kernel 6.6.87.2-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-6.6.87.2-microsoft-standard-WSL2
    linux-cloud-tools-6.6.87.2-microsoft-standard-WSL2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard-WSL2
    linux-cloud-tools-standard-WSL2
```
